package namba

import (
	"fmt"
	"strings"
)

const (
	readmeProfileManagedProject = "managed-project"
	readmeProfileNambaCLI       = "namba-cli"
	nambaRepositoryURL          = "https://github.com/Nam-Cheol/namba-ai"
)

func defaultDocsConfig(projectType string) docsConfig {
	manage := strings.TrimSpace(projectType) == "new"
	return docsConfig{
		ManageReadme:        manage,
		ReadmeProfile:       readmeProfileManagedProject,
		DefaultLanguage:     "en",
		AdditionalLanguages: []string{"ko", "ja", "zh"},
	}
}

func normalizeDocsConfig(cfg docsConfig, projectType string) docsConfig {
	defaults := defaultDocsConfig(projectType)
	if strings.TrimSpace(cfg.ReadmeProfile) == "" {
		cfg.ReadmeProfile = defaults.ReadmeProfile
	}
	switch cfg.ReadmeProfile {
	case readmeProfileManagedProject, readmeProfileNambaCLI:
	default:
		cfg.ReadmeProfile = defaults.ReadmeProfile
	}
	cfg.DefaultLanguage = normalizeReadmeLanguage(firstNonBlank(cfg.DefaultLanguage, defaults.DefaultLanguage))
	if !cfg.AdditionalLanguagesSet && len(cfg.AdditionalLanguages) == 0 {
		cfg.AdditionalLanguages = defaults.AdditionalLanguages
	}
	cfg.AdditionalLanguages = uniqueReadmeLanguages(cfg.AdditionalLanguages)
	return cfg
}

func parseCommaSeparatedList(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	var values []string
	for _, part := range parts {
		if value := strings.TrimSpace(part); value != "" {
			values = append(values, value)
		}
	}
	return values
}

func buildReadmeOutputs(projectCfg projectConfig, profile initProfile, cfg docsConfig) map[string]string {
	cfg = normalizeDocsConfig(cfg, projectCfg.ProjectType)
	if !cfg.ManageReadme {
		return nil
	}

	outputs := make(map[string]string)
	for _, lang := range readmeLanguages(cfg) {
		outputs[readmePath(lang)] = renderReadmeRoot(lang, projectCfg, profile, cfg)
		outputs[guidePath("getting-started", lang)] = renderReadmeGuide(lang, "getting-started", projectCfg, profile, cfg)
		outputs[guidePath("workflow-guide", lang)] = renderReadmeGuide(lang, "workflow-guide", projectCfg, profile, cfg)
	}
	return outputs
}

func readmeLanguages(cfg docsConfig) []string {
	languages := []string{normalizeReadmeLanguage(cfg.DefaultLanguage)}
	languages = append(languages, cfg.AdditionalLanguages...)
	return uniqueReadmeLanguages(languages)
}

func uniqueReadmeLanguages(values []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, value := range values {
		lang := normalizeReadmeLanguage(value)
		if seen[lang] {
			continue
		}
		seen[lang] = true
		result = append(result, lang)
	}
	return result
}

func normalizeReadmeLanguage(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "ko", "kr":
		return "ko"
	case "ja", "jp":
		return "ja"
	case "zh", "cn", "zh-cn", "zh-hans", "zh-hant", "tw":
		return "zh"
	default:
		return "en"
	}
}

func readmePath(lang string) string {
	if normalizeReadmeLanguage(lang) == "en" {
		return "README.md"
	}
	return fmt.Sprintf("README.%s.md", normalizeReadmeLanguage(lang))
}

func guidePath(base, lang string) string {
	lang = normalizeReadmeLanguage(lang)
	if lang == "en" {
		return fmt.Sprintf("docs/%s.md", base)
	}
	return fmt.Sprintf("docs/%s.%s.md", base, lang)
}

func isReadmeManagedPath(rel string) bool {
	switch {
	case rel == readmePath("en"):
		return true
	case strings.HasPrefix(rel, "README.") && strings.HasSuffix(rel, ".md"):
		return true
	case isGeneratedGuidePath(rel, "getting-started"):
		return true
	case isGeneratedGuidePath(rel, "workflow-guide"):
		return true
	default:
		return false
	}
}

func isGeneratedGuidePath(rel, base string) bool {
	defaultPath := guidePath(base, "en")
	if rel == defaultPath {
		return true
	}
	return strings.HasPrefix(rel, "docs/"+base+".") && strings.HasSuffix(rel, ".md")
}

func renderReadmeRoot(lang string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	switch cfg.ReadmeProfile {
	case readmeProfileNambaCLI:
		return renderNambaCLIRoot(lang, cfg)
	default:
		return renderManagedProjectRoot(lang, projectCfg, profile, cfg)
	}
}

func renderReadmeGuide(lang, guide string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	switch cfg.ReadmeProfile {
	case readmeProfileNambaCLI:
		return renderNambaCLIGuide(lang, guide)
	default:
		return renderManagedProjectGuide(lang, guide, projectCfg, profile)
	}
}

func renderGeneratedDocHeader() string {
	return "<!-- Generated by `namba sync`. Edit `.namba/config/sections/docs.yaml` or the README renderer instead of editing this file directly. -->\n"
}

func renderHeroBlock(heroPath, alt string) string {
	if strings.TrimSpace(heroPath) == "" {
		return ""
	}
	return strings.Join([]string{
		"<p align=\"center\">",
		fmt.Sprintf("  <img src=\"%s\" alt=\"%s\" width=\"100%%\" />", heroPath, alt),
		"</p>",
		"",
	}, "\n")
}

func renderLanguageLinks(prefix string) string {
	links := []string{
		fmt.Sprintf("[English](%s%s)", prefix, readmePath("en")),
		fmt.Sprintf("[한국어](%s%s)", prefix, readmePath("ko")),
		fmt.Sprintf("[日本語](%s%s)", prefix, readmePath("ja")),
		fmt.Sprintf("[中文](%s%s)", prefix, readmePath("zh")),
	}
	return strings.Join(links, " | ")
}

func renderRootLinkBar() string {
	return fmt.Sprintf("[Latest Release](%s/releases/latest) | [CI](%s/actions/workflows/ci.yml) | [Security](SECURITY.md)", nambaRepositoryURL, nambaRepositoryURL)
}

func guideFilename(base, lang string) string {
	lang = normalizeReadmeLanguage(lang)
	if lang == "en" {
		return fmt.Sprintf("%s.md", base)
	}
	return fmt.Sprintf("%s.%s.md", base, lang)
}

func localizeGuideLabel(lang, guide string) string {
	lang = normalizeReadmeLanguage(lang)
	switch guide {
	case "workflow-guide":
		switch lang {
		case "ko":
			return "워크플로 가이드"
		case "ja":
			return "ワークフローガイド"
		case "zh":
			return "工作流指南"
		default:
			return "Workflow Guide"
		}
	default:
		switch lang {
		case "ko":
			return "시작 가이드"
		case "ja":
			return "スタートガイド"
		case "zh":
			return "上手指南"
		default:
			return "Getting Started"
		}
	}
}

func renderDocLinkBar(lang string) string {
	return strings.Join([]string{
		fmt.Sprintf("[%s](./%s)", localizeGuideLabel(lang, "getting-started"), guideFilename("getting-started", lang)),
		fmt.Sprintf("[%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
		"[Codex Upstream Reference](./codex-upstream-reference.md)",
	}, " | ")
}

func renderNambaCLIRoot(lang string, cfg docsConfig) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"Codex 네이티브 방식으로 저장소를 초기화하고, 작업을 SPEC 단위로 계획하고, 구현 이후 산출물까지 정리하는 개발 워크플로입니다.",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## 사용자는 무엇을 할 수 있나",
			"",
			"- 빈 디렉터리에서 `namba init .`로 Codex-ready 저장소를 바로 시작할 수 있습니다.",
			"- `namba plan`, `namba fix`로 요청을 SPEC 패키지로 정리하고 작업 범위를 유지할 수 있습니다.",
			"- `namba run SPEC-XXX`와 `namba sync`로 구현, 검증, PR 준비 산출물을 한 흐름으로 마무리할 수 있습니다.",
			"- `namba update`와 릴리스 기반 배포 흐름으로 팀 전체 CLI 버전을 맞출 수 있습니다.",
			"",
			"## 빠른 시작",
			"",
			"### 1. NambaAI 설치",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 새 저장소 초기화",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Codex에서 작업 시작",
			"",
			"```text",
			"namba project",
			"namba plan \"로그인 감사 로그 추가\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 더 자세히 보기",
			"",
			fmt.Sprintf("- [%s](%s): 설치, 초기화, 업데이트, 첫 실행 흐름", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync 차이, 산출물, 협업 규칙", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): 이 저장소가 맞추는 Codex 기준",
			"- [SECURITY.md](SECURITY.md): 보안 정책",
			"",
			"## 기술 요약",
			"",
			"- `.namba/`는 설정, SPEC, 프로젝트 문서의 source of truth입니다.",
			"- `.agents/skills/`는 Codex가 읽는 repo-local skill surface입니다.",
			"- `.codex/agents/*.toml`은 planner, implementer, reviewer용 custom agent 정의입니다.",
			"- `namba update`, `namba regen`, `namba sync`는 역할이 다르며 서로 대체하지 않습니다.",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI は、Codex ネイティブでリポジトリを初期化し、作業を SPEC 単位で計画し、実装後の成果物まで同期する開発ワークフローです。",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## NambaAI でできること",
			"",
			"- 空のディレクトリで `namba init .` を実行し、Codex-ready なリポジトリをすぐに開始できます。",
			"- `namba plan` と `namba fix` で依頼を SPEC パッケージに整理し、作業範囲を安定させられます。",
			"- `namba run SPEC-XXX` と `namba sync` で実装、検証、PR 準備を一連の流れで完了できます。",
			"- `namba update` とリリース配布で、チーム全体の CLI バージョンを揃えられます。",
			"",
			"## クイックスタート",
			"",
			"### 1. NambaAI をインストール",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 新しいリポジトリを初期化",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Codex で作業を開始",
			"",
			"```text",
			"namba project",
			"namba plan \"ログイン監査ログを追加\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## さらに詳しく",
			"",
			fmt.Sprintf("- [%s](%s): インストール、初期化、更新、最初の実行", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync の違い、成果物、協業ルール", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): このリポジトリが合わせている Codex の基準",
			"- [SECURITY.md](SECURITY.md): セキュリティポリシー",
			"",
			"## 技術スナップショット",
			"",
			"- `.namba/` は設定、SPEC、プロジェクト文書の source of truth です。",
			"- `.agents/skills/` は Codex が読む repo-local skill surface です。",
			"- `.codex/agents/*.toml` は planner、implementer、reviewer 向け custom agent 定義です。",
			"- `namba update`、`namba regen`、`namba sync` はそれぞれ役割が異なります。",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI 是一套面向 Codex 的开发工作流，用来初始化仓库、以 SPEC 形式规划工作，并在实现后同步项目产物。",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## 你可以用 NambaAI 做什么",
			"",
			"- 在空目录中执行 `namba init .`，快速得到可直接用于 Codex 的仓库。",
			"- 用 `namba plan` 和 `namba fix` 把需求整理成 SPEC 包，保持范围清晰。",
			"- 用 `namba run SPEC-XXX` 和 `namba sync` 完成实现、校验与 PR 准备。",
			"- 通过 `namba update` 和发布资产，让团队统一 CLI 版本。",
			"",
			"## 快速开始",
			"",
			"### 1. 安装 NambaAI",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 初始化一个新仓库",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. 在 Codex 中开始工作",
			"",
			"```text",
			"namba project",
			"namba plan \"添加登录审计日志\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 进一步了解",
			"",
			fmt.Sprintf("- [%s](%s): 安装、初始化、更新与首次运行", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync 的区别、产物与协作规则", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): 本仓库遵循的 Codex 参考",
			"- [SECURITY.md](SECURITY.md): 安全策略",
			"",
			"## 技术概览",
			"",
			"- `.namba/` 是配置、SPEC 和项目文档的 source of truth。",
			"- `.agents/skills/` 是 Codex 实际读取的 repo-local skill surface。",
			"- `.codex/agents/*.toml` 定义了 planner、implementer、reviewer 的 custom agent。",
			"- `namba update`、`namba regen`、`namba sync` 负责不同职责，不能互相替代。",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI is a Codex-native workflow for bootstrapping repositories, planning work as SPEC packages, and syncing project artifacts after implementation.",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## What You Can Do With NambaAI",
			"",
			"- Bootstrap a Codex-ready repository from an empty directory with `namba init .`.",
			"- Turn change requests into SPEC packages with `namba plan` and `namba fix`.",
			"- Execute work with `namba run SPEC-XXX` for the default flow, use `--solo` or `--team` for standalone subagent-oriented runs, or `--parallel` for worktree fan-out before handing off with `namba sync`, `namba pr`, and `namba land`.",
			"- Keep CLI versions aligned across the team with `namba update` and release assets.",
			"",
			"## Quick Start",
			"",
			"### 1. Install NambaAI",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. Bootstrap a new repository",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Start working from Codex",
			"",
			"```text",
			"namba project",
			"namba plan \"add login audit logs\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add login audit logs\"",
			"namba land",
			"```",
			"",
			"## Command Skills In Codex",
			"",
			"- `$namba`: general router when you want Codex to choose the right Namba workflow entry point.",
			"- `$namba-project`: refresh project docs and codemaps before starting or after larger changes.",
			"- `$namba-plan` / `$namba-fix`: create the next feature or bugfix SPEC package.",
			"- `$namba-run`: execute a SPEC package through the Namba workflow in the current Codex session.",
			"- `$namba-sync`: refresh README bundles, project docs, codemaps, and PR-ready artifacts.",
			"- `$namba-pr` / `$namba-land`: hand off the current branch for GitHub review, then merge it safely after checks pass.",
			"- `$namba-regen` / `$namba-update`: regenerate repo-local Codex assets or self-update the installed `namba` CLI.",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Custom Agents In Codex",
			"",
			"- Strategy: `namba-product-manager` shapes scope and acceptance, and `namba-planner` turns a SPEC into an execution plan.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, and `namba-designer` cover web UI, mobile execution, and visual direction.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, and `namba-data-engineer` cover APIs, persistence, migrations, and pipelines.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, and `namba-reviewer` cover hardening, regression confidence, CI/CD, and final acceptance.",
			"- General delivery: `namba-implementer` remains the generalist execution agent when a task spans multiple domains but does not justify a larger specialist team.",
			"",
			"## Need More Detail?",
			"",
			fmt.Sprintf("- [%s](%s): installation, init, updates, and first-run flow", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update vs regen vs sync vs pr vs land, run modes, generated assets, and collaboration defaults", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): upstream baseline this repository follows",
			"- [SECURITY.md](SECURITY.md): security policy",
			"",
			"## Technical Snapshot",
			"",
			"- `.namba/` is the source of truth for config, SPEC packages, and project docs.",
			"- `.agents/skills/` is the repo-local skill surface used by Codex.",
			"- `.codex/agents/*.toml` defines task-oriented custom agents across product, planning, design, frontend, mobile, backend, data, security, testing, ops, implementation, and review.",
			"- `namba update`, `namba regen`, `namba sync`, `namba pr`, and `namba land` solve different problems and should not be mixed.",
			"",
		}, "\n")
	}
}

func renderManagedProjectRoot(lang string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	title := projectCfg.Name
	if title == "" {
		title = "Project"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"NambaAI가 관리하는 Codex 네이티브 작업 저장소입니다. 이 README는 저장소를 처음 여는 사람이 바로 작업 흐름을 이해하도록 `namba sync`가 생성합니다.",
			"",
			renderLanguageLinks(""),
			"",
			"## 이 저장소에서 할 수 있는 일",
			"",
			"- `namba project`로 현재 프로젝트 구조와 핵심 문서를 새로 읽을 수 있습니다.",
			"- `namba plan` 또는 `namba fix`로 요청을 SPEC 패키지로 정리할 수 있습니다.",
			"- `namba run SPEC-XXX`로 구현을 진행하고 검증을 거친 뒤 `namba sync`로 산출물을 정리할 수 있습니다.",
			"- 브랜치, PR, Codex 리뷰 흐름을 같은 규칙으로 유지할 수 있습니다.",
			"",
			"## 빠르게 시작하기",
			"",
			"```text",
			"namba project",
			"namba plan \"작업 설명\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 더 보기",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 현재 기본 규칙",
			"",
			fmt.Sprintf("- 작업 언어: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR 대상 브랜치: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex 리뷰 코멘트: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"このリポジトリは NambaAI で管理されています。初めて開いた人が作業フローをすぐ理解できるように、この README は `namba sync` によって生成されます。",
			"",
			renderLanguageLinks(""),
			"",
			"## このリポジトリでできること",
			"",
			"- `namba project` で現在の構成と主要ドキュメントを更新できます。",
			"- `namba plan` または `namba fix` で依頼を SPEC パッケージに整理できます。",
			"- `namba run SPEC-XXX` で実装を進め、検証後に `namba sync` で成果物を整理できます。",
			"- ブランチ、PR、Codex レビューの流れを同じルールで維持できます。",
			"",
			"## すぐ始める",
			"",
			"```text",
			"namba project",
			"namba plan \"作業内容\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## さらに読む",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 現在の既定値",
			"",
			fmt.Sprintf("- 作業言語: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR ベースブランチ: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex レビューコメント: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"这个仓库由 NambaAI 管理。为了让第一次打开仓库的人快速理解工作流，这份 README 会由 `namba sync` 生成。",
			"",
			renderLanguageLinks(""),
			"",
			"## 你可以在这个仓库里做什么",
			"",
			"- 用 `namba project` 刷新当前项目结构和核心文档。",
			"- 用 `namba plan` 或 `namba fix` 把需求整理成 SPEC 包。",
			"- 用 `namba run SPEC-XXX` 执行实现，并在校验后用 `namba sync` 整理产物。",
			"- 用统一规则维护分支、PR 和 Codex 评审流程。",
			"",
			"## 快速开始",
			"",
			"```text",
			"namba project",
			"namba plan \"工作说明\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 继续阅读",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 当前默认值",
			"",
			fmt.Sprintf("- 工作语言: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR 基准分支: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex 评审评论: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"This repository is managed with NambaAI. The README is generated by `namba sync` so contributors can understand the workflow before they touch the code.",
			"",
			renderLanguageLinks(""),
			"",
			"## What You Can Do In This Repository",
			"",
			"- Run `namba project` to refresh the current structure and core docs.",
			"- Use `namba plan` or `namba fix` to package requests as SPEC work.",
			"- Execute `namba run SPEC-XXX` for the default flow, or use `--solo`, `--team`, and `--parallel` when the task needs single-specialist, small-team, or worktree fan-out execution.",
			"- Keep branch, PR, and Codex review flow consistent across contributors.",
			"",
			"## Start Fast",
			"",
			"```text",
			"namba project",
			"namba plan \"work description\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
			"## Command Skills In Codex",
			"",
			"- `$namba`: general router when you want Codex to choose the right Namba entry point.",
			"- `$namba-project`: refresh docs and codemaps before implementation or after larger changes.",
			"- `$namba-plan` / `$namba-fix`: create the next feature or bug-fix SPEC package.",
			"- `$namba-run`: execute the current SPEC package with the Namba run workflow.",
			"- `$namba-sync`: refresh README bundles, project docs, codemaps, and PR-ready artifacts.",
			"- `$namba-pr` / `$namba-land`: prepare GitHub review handoff, then merge safely after checks pass.",
			"- `$namba-regen` / `$namba-update`: regenerate repo-local Codex assets or update the installed `namba` CLI.",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Custom Agents In Codex",
			"",
			"- Strategy: `namba-product-manager` shapes scope and acceptance, and `namba-planner` turns a SPEC into an execution plan.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, and `namba-designer` cover web UI, mobile execution, and visual direction.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, and `namba-data-engineer` cover APIs, persistence, migrations, and pipelines.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, and `namba-reviewer` cover hardening, regression confidence, CI/CD, and final acceptance.",
			"- General delivery: `namba-implementer` remains available when a task spans multiple domains but does not justify a larger specialist roster.",
			"",
			"## Read More",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## Current Defaults",
			"",
			fmt.Sprintf("- Working language: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR base branch: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex review comment: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	}
}

func renderNambaCLIGuide(lang, guide string) string {
	switch guide {
	case "workflow-guide":
		return renderNambaCLIWorkflowGuide(lang)
	default:
		return renderNambaCLIGettingStarted(lang)
	}
}

func renderManagedProjectGuide(lang, guide string, projectCfg projectConfig, profile initProfile) string {
	switch guide {
	case "workflow-guide":
		return renderManagedProjectWorkflowGuide(lang, projectCfg, profile)
	default:
		return renderManagedProjectGettingStarted(lang, projectCfg)
	}
}

func renderNambaCLIGettingStarted(lang string) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 설치",
			"",
			"- Windows: `irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex`",
			"- macOS / Linux: `curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh`",
			"- 특정 버전 설치나 업데이트는 `namba update --version vX.Y.Z`를 사용합니다.",
			"",
			"## 2. 새 저장소 초기화",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard에서는 작업 언어, approval_policy, sandbox_mode, PR 언어, Codex agent mode를 함께 고를 수 있습니다.",
			"",
			"## 3. Codex에서 기본 흐름 실행",
			"",
			"```text",
			"namba project",
			"namba plan \"대시보드 필터 추가\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 4. 다음에 보면 좋은 문서",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. インストール",
			"",
			"- Windows: `irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex`",
			"- macOS / Linux: `curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh`",
			"- 特定バージョンへの更新は `namba update --version vX.Y.Z` を使います。",
			"",
			"## 2. 新しいリポジトリを初期化",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard では作業言語、approval_policy、sandbox_mode、PR 言語、Codex agent mode をまとめて選べます。",
			"",
			"## 3. Codex で基本フローを実行",
			"",
			"```text",
			"namba project",
			"namba plan \"ダッシュボードフィルタを追加\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 4. 次に読む文書",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 安装",
			"",
			"- Windows: `irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex`",
			"- macOS / Linux: `curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh`",
			"- 指定版本更新可使用 `namba update --version vX.Y.Z`。",
			"",
			"## 2. 初始化新仓库",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard 中可以一起选择工作语言、approval_policy、sandbox_mode、PR 语言和 Codex agent mode。",
			"",
			"## 3. 在 Codex 中执行基本流程",
			"",
			"```text",
			"namba project",
			"namba plan \"添加仪表盘筛选\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 4. 下一步建议阅读",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. Install",
			"",
			"- Windows: `irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex`",
			"- macOS / Linux: `curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh`",
			"- Use `namba update --version vX.Y.Z` when you need a specific CLI version.",
			"",
			"## 2. Bootstrap a new repository",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"The wizard aligns working language, approval_policy, sandbox_mode, PR language, and Codex agent mode.",
			"",
			"## 3. Run the basic Codex flow",
			"",
			"```text",
			"namba project",
			"namba plan \"add dashboard filters\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 4. Read next",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		}, "\n")
	}
}

func renderNambaCLIWorkflowGuide(lang string) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`, `regen`, `sync`는 다릅니다",
			"",
			"- `namba update`: 설치된 `namba` CLI를 GitHub Release 기준으로 self-update",
			"- `namba regen`: AGENTS, skills, custom agents, Codex config 같은 template-generated 자산 재생성",
			"- `namba sync`: README, 프로젝트 문서, codemap, PR 체크리스트, 릴리스 메모 같은 사용자/협업 문서 갱신",
			"",
			"## 생성되는 핵심 자산",
			"",
			"- `.namba/`: 설정, SPEC, project docs, logs",
			"- `.agents/skills/`: Codex가 직접 읽는 repo-local skills",
			"- `.codex/agents/*.toml`: custom subagents",
			"- `.namba/project/*`: change summary, release notes, checklist, codemap",
			"",
			"## 협업 기본값",
			"",
			"- 작업은 전용 브랜치에서 진행합니다.",
			"- PR은 `main` 대상으로 엽니다.",
			"- PR 제목/본문은 선택된 PR 언어를 따릅니다.",
			"- GitHub에서 `@codex review`를 요청합니다.",
			"",
			"## 릴리스 흐름",
			"",
			"- `namba release`는 clean working tree와 `main` 브랜치를 요구합니다.",
			"- `--push`를 쓰면 tag와 `main`을 함께 푸시하고 GitHub Release 워크플로를 트리거합니다.",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`、`regen`、`sync` は別物です",
			"",
			"- `namba update`: インストール済み CLI を GitHub Release ベースで self-update",
			"- `namba regen`: AGENTS、skills、custom agents、Codex config などの template-generated assets を再生成",
			"- `namba sync`: README、プロジェクト文書、codemap、PR checklist、release notes を更新",
			"",
			"## 生成される主要アセット",
			"",
			"- `.namba/`: config, specs, project docs, logs",
			"- `.agents/skills/`: Codex が直接読む repo-local skills",
			"- `.codex/agents/*.toml`: custom subagents",
			"- `.namba/project/*`: change summary、release notes、checklist、codemap",
			"",
			"## 協業の既定値",
			"",
			"- 作業は専用ブランチで進めます。",
			"- PR は `main` を対象にします。",
			"- PR の題名と本文は選択した PR 言語に従います。",
			"- GitHub で `@codex review` を依頼します。",
			"",
			"## リリースフロー",
			"",
			"- `namba release` は clean working tree と `main` ブランチを要求します。",
			"- `--push` を使うと tag と `main` を一緒に push し、GitHub Release workflow を起動します。",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`、`regen`、`sync` 是不同命令",
			"",
			"- `namba update`: 按 GitHub Release 更新已安装的 CLI",
			"- `namba regen`: 重新生成 AGENTS、skills、custom agents、Codex config 等模板产物",
			"- `namba sync`: 刷新 README、项目文档、codemap、PR checklist、release notes",
			"",
			"## 关键产物",
			"",
			"- `.namba/`: config, specs, project docs, logs",
			"- `.agents/skills/`: Codex 直接读取的 repo-local skills",
			"- `.codex/agents/*.toml`: custom subagents",
			"- `.namba/project/*`: change summary、release notes、checklist、codemap",
			"",
			"## 协作默认值",
			"",
			"- 所有工作都在专用分支上进行。",
			"- PR 目标分支是 `main`。",
			"- PR 标题和正文遵循所选 PR 语言。",
			"- 在 GitHub 上请求 `@codex review`。",
			"",
			"## 发布流程",
			"",
			"- `namba release` 要求 clean working tree 和 `main` 分支。",
			"- 使用 `--push` 时会同时推送 tag 和 `main`，并触发 GitHub Release workflow。",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`, `regen`, `sync`, `pr`, and `land` are different commands",
			"",
			"- `namba update`: self-update the installed CLI from GitHub Release assets",
			"- `namba regen`: regenerate AGENTS, skills, custom agents, and repo Codex config",
			"- `namba sync`: refresh README, project docs, codemaps, PR checklists, and release notes",
			"- `namba pr`: run sync plus validation by default, commit and push the current branch, open or reuse the PR, and ensure the Codex review marker exists",
			"- `namba land`: optionally wait for checks, merge only when the PR is clean, and update local `main` safely",
			"",
			"## `namba run` modes",
			"",
			"- `namba run SPEC-XXX`: standard standalone Codex flow in one workspace.",
			"- `namba run SPEC-XXX --solo`: standalone single-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --team`: standalone multi-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --parallel`: Namba-managed git worktree fan-out/fan-in, not Codex subagent orchestration.",
			"",
			"## Role routing",
			"",
			"- Default `namba run` stays in the standalone runner unless the prompt shows a strong specialist signal.",
			"- `--solo` uses at most one specialist when one domain clearly dominates; `--team` expands to two specialists plus reviewer only when acceptance spans multiple domains.",
			"- Route UI, responsive, mobile, and design work to `namba-frontend-implementer`, `namba-mobile-engineer`, or `namba-designer`; API, schema, and pipeline work to `namba-backend-implementer` or `namba-data-engineer`; auth, secrets, and compliance work to `namba-security-engineer`; deployment and runtime work to `namba-devops-engineer`.",
			"- Keep the standalone runner as integrator and validation owner; use `namba-reviewer` for the final acceptance pass rather than growing an uncontrolled swarm.",
			"",
			"## Key generated assets",
			"",
			"- `.namba/`: config, SPEC packages, project docs, logs",
			"- `.agents/skills/`: repo-local skills used directly by Codex",
			"- `.codex/agents/*.toml`: custom subagents",
			"- `.namba/project/*`: change summary, release notes, checklist, codemap",
			"",
			"## Collaboration defaults",
			"",
			"- Work happens on dedicated branches.",
			"- `namba pr` targets `main` and keeps the configured PR language plus review marker aligned.",
			"- `namba land` merges only clean PRs and updates local `main` without clobbering unrelated work.",
			"- GitHub review requests use `@codex review`.",
			"",
			"## Release flow",
			"",
			"- `namba release` requires a clean working tree on `main`.",
			"- `--push` pushes both the new tag and `main`, then triggers the GitHub Release workflow.",
			"",
		}, "\n")
	}
}

func renderManagedProjectGettingStarted(lang string, projectCfg projectConfig) string {
	projectName := projectCfg.Name
	if projectName == "" {
		projectName = "this repository"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 저장소 열기",
			"",
			fmt.Sprintf("- `%s` 루트에서 Codex를 실행합니다.", projectName),
			"- `namba doctor`로 기본 준비 상태를 확인할 수 있습니다.",
			"",
			"## 2. 현재 컨텍스트 갱신",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 작업 패키지 만들기",
			"",
			"- 기능 작업: `namba plan \"설명\"`",
			"- 버그 수정: `namba fix \"설명\"`",
			"",
			"## 4. 구현과 정리",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. リポジトリを開く",
			"",
			fmt.Sprintf("- `%s` のルートで Codex を起動します。", projectName),
			"- `namba doctor` で準備状態を確認できます。",
			"",
			"## 2. 現在のコンテキストを更新",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 作業パッケージを作る",
			"",
			"- 機能作業: `namba plan \"説明\"`",
			"- バグ修正: `namba fix \"説明\"`",
			"",
			"## 4. 実装と同期",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 打开仓库",
			"",
			fmt.Sprintf("- 在 `%s` 根目录启动 Codex。", projectName),
			"- 可用 `namba doctor` 检查准备状态。",
			"",
			"## 2. 刷新当前上下文",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 创建工作包",
			"",
			"- 功能需求: `namba plan \"说明\"`",
			"- 缺陷修复: `namba fix \"说明\"`",
			"",
			"## 4. 实现并同步",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. Open the repository",
			"",
			fmt.Sprintf("- Start Codex from the root of `%s`.", projectName),
			"- Run `namba doctor` if you want a quick readiness check.",
			"",
			"## 2. Refresh current context",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. Create a work package",
			"",
			"- Feature request: `namba plan \"description\"`",
			"- Bug fix: `namba fix \"description\"`",
			"",
			"## 4. Implement and sync",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 5. Hand off and merge",
			"",
			"```text",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
		}, "\n")
	}
}

func renderManagedProjectWorkflowGuide(lang string, projectCfg projectConfig, profile initProfile) string {
	projectName := projectCfg.Name
	if projectName == "" {
		projectName = "this repository"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s`는 NambaAI 기준으로 관리됩니다.", projectName),
			"",
			"## 저장소에서 보는 핵심 위치",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.agents/skills/`: Codex가 직접 읽는 skills",
			"- `.codex/agents/*.toml`: custom subagents",
			"",
			"## 작업 순서",
			"",
			"1. `namba project`",
			"2. `namba plan` 또는 `namba fix`",
			"3. `namba run SPEC-XXX`",
			"4. `namba sync`",
			"",
			"## 협업 규칙",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` は NambaAI の規則で管理されています。", projectName),
			"",
			"## 主要な場所",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.agents/skills/`: Codex が直接読む skills",
			"- `.codex/agents/*.toml`: custom subagents",
			"",
			"## 作業順序",
			"",
			"1. `namba project`",
			"2. `namba plan` または `namba fix`",
			"3. `namba run SPEC-XXX`",
			"4. `namba sync`",
			"",
			"## 協業ルール",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` 按照 NambaAI 规则进行管理。", projectName),
			"",
			"## 关键位置",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.agents/skills/`: Codex 直接读取的 skills",
			"- `.codex/agents/*.toml`: custom subagents",
			"",
			"## 工作顺序",
			"",
			"1. `namba project`",
			"2. `namba plan` 或 `namba fix`",
			"3. `namba run SPEC-XXX`",
			"4. `namba sync`",
			"",
			"## 协作规则",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` is managed with NambaAI conventions.", projectName),
			"",
			"## Key locations",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.agents/skills/`: skills used directly by Codex",
			"- `.codex/agents/*.toml`: custom subagents",
			"",
			"## Work order",
			"",
			"1. `namba project`",
			"2. `namba plan` or `namba fix`",
			"3. `namba run SPEC-XXX`",
			"4. `namba sync`",
			"5. `namba pr \"review title\"`",
			"6. `namba land`",
			"",
			"## Run modes",
			"",
			"- `namba run SPEC-XXX`: standard standalone Codex flow in one workspace.",
			"- `namba run SPEC-XXX --solo`: standalone single-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --team`: standalone multi-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --parallel`: Namba-managed git worktree fan-out/fan-in, not Codex subagent orchestration.",
			"",
			"## Role routing",
			"",
			"- Default `namba run` stays inside the standalone runner unless specialist signals are strong enough to justify delegation.",
			"- `--solo` uses at most one specialist when one domain clearly dominates the request.",
			"- `--team` prefers one specialist when one domain dominates and expands to two or three only when acceptance spans multiple domains.",
			"- Route UI, responsive, mobile, and design work to `namba-frontend-implementer`, `namba-mobile-engineer`, or `namba-designer`; API, schema, and pipeline work to `namba-backend-implementer` or `namba-data-engineer`; auth, secrets, and compliance work to `namba-security-engineer`; deployment and runtime work to `namba-devops-engineer`.",
			"- Keep the standalone runner as integrator and validation owner, and use `namba-reviewer` last when multiple specialists contribute.",
			"",
			"## Collaboration rules",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"- `namba sync` stays local; `namba pr` and `namba land` handle GitHub handoff plus merge.",
			"",
		}, "\n")
	}
}
