package namba

import (
	"fmt"
	"strings"
)

const (
	readmeProfileManagedProject = "managed-project"
	readmeProfileNambaCLI       = "namba-cli"
	nambaRepositoryURL          = "https://github.com/Nam-Cheol/namba-ai"
	nambaInstallPowerShell      = "irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex"
	nambaInstallShell           = "curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh"
	nambaWindowsInstallDir      = "%LOCALAPPDATA%\\Programs\\NambaAI\\bin"
	nambaWindowsBinaryPath      = "%LOCALAPPDATA%\\Programs\\NambaAI\\bin\\namba.exe"
	nambaUnixBinaryPath         = "~/.local/bin/namba"
)

func defaultDocsConfig(projectType string) docsConfig {
	manage := strings.TrimSpace(projectType) == "new"
	return docsConfig{
		ManageReadme:        manage,
		ReadmeProfile:       readmeProfileManagedProject,
		DefaultLanguage:     "en",
		AdditionalLanguages: []string{"ko", "ja", "zh"},
	}
}

func normalizeDocsConfig(cfg docsConfig, projectType string) docsConfig {
	defaults := defaultDocsConfig(projectType)
	if strings.TrimSpace(cfg.ReadmeProfile) == "" {
		cfg.ReadmeProfile = defaults.ReadmeProfile
	}
	switch cfg.ReadmeProfile {
	case readmeProfileManagedProject, readmeProfileNambaCLI:
	default:
		cfg.ReadmeProfile = defaults.ReadmeProfile
	}
	cfg.DefaultLanguage = normalizeReadmeLanguage(firstNonBlank(cfg.DefaultLanguage, defaults.DefaultLanguage))
	if !cfg.AdditionalLanguagesSet && len(cfg.AdditionalLanguages) == 0 {
		cfg.AdditionalLanguages = defaults.AdditionalLanguages
	}
	cfg.AdditionalLanguages = uniqueReadmeLanguages(cfg.AdditionalLanguages)
	return cfg
}

func parseCommaSeparatedList(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	var values []string
	for _, part := range parts {
		if value := strings.TrimSpace(part); value != "" {
			values = append(values, value)
		}
	}
	return values
}

func buildReadmeOutputs(projectCfg projectConfig, profile initProfile, cfg docsConfig) map[string]string {
	cfg = normalizeDocsConfig(cfg, projectCfg.ProjectType)
	if !cfg.ManageReadme {
		return nil
	}

	outputs := make(map[string]string)
	for _, lang := range readmeLanguages(cfg) {
		outputs[readmePath(lang)] = renderReadmeRoot(lang, projectCfg, profile, cfg)
		outputs[guidePath("getting-started", lang)] = renderReadmeGuide(lang, "getting-started", projectCfg, profile, cfg)
		outputs[guidePath("workflow-guide", lang)] = renderReadmeGuide(lang, "workflow-guide", projectCfg, profile, cfg)
	}
	return outputs
}

func readmeLanguages(cfg docsConfig) []string {
	languages := []string{normalizeReadmeLanguage(cfg.DefaultLanguage)}
	languages = append(languages, cfg.AdditionalLanguages...)
	return uniqueReadmeLanguages(languages)
}

func uniqueReadmeLanguages(values []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, value := range values {
		lang := normalizeReadmeLanguage(value)
		if seen[lang] {
			continue
		}
		seen[lang] = true
		result = append(result, lang)
	}
	return result
}

func normalizeReadmeLanguage(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "ko", "kr":
		return "ko"
	case "ja", "jp":
		return "ja"
	case "zh", "cn", "zh-cn", "zh-hans", "zh-hant", "tw":
		return "zh"
	default:
		return "en"
	}
}

func readmePath(lang string) string {
	if normalizeReadmeLanguage(lang) == "en" {
		return "README.md"
	}
	return fmt.Sprintf("README.%s.md", normalizeReadmeLanguage(lang))
}

func guidePath(base, lang string) string {
	lang = normalizeReadmeLanguage(lang)
	if lang == "en" {
		return fmt.Sprintf("docs/%s.md", base)
	}
	return fmt.Sprintf("docs/%s.%s.md", base, lang)
}

func isReadmeManagedPath(rel string) bool {
	switch {
	case rel == readmePath("en"):
		return true
	case strings.HasPrefix(rel, "README.") && strings.HasSuffix(rel, ".md"):
		return true
	case isGeneratedGuidePath(rel, "getting-started"):
		return true
	case isGeneratedGuidePath(rel, "workflow-guide"):
		return true
	default:
		return false
	}
}

func isGeneratedGuidePath(rel, base string) bool {
	defaultPath := guidePath(base, "en")
	if rel == defaultPath {
		return true
	}
	return strings.HasPrefix(rel, "docs/"+base+".") && strings.HasSuffix(rel, ".md")
}

func renderReadmeRoot(lang string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	switch cfg.ReadmeProfile {
	case readmeProfileNambaCLI:
		return renderNambaCLIRoot(lang, cfg)
	default:
		return renderManagedProjectRoot(lang, projectCfg, profile, cfg)
	}
}

func renderReadmeGuide(lang, guide string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	switch cfg.ReadmeProfile {
	case readmeProfileNambaCLI:
		return renderNambaCLIGuide(lang, guide)
	default:
		return renderManagedProjectGuide(lang, guide, projectCfg, profile)
	}
}

func renderGeneratedDocHeader() string {
	return "<!-- Generated by `namba sync`. Edit `.namba/config/sections/docs.yaml` or the README renderer instead of editing this file directly. -->\n"
}

func renderHeroBlock(heroPath, alt string) string {
	if strings.TrimSpace(heroPath) == "" {
		return ""
	}
	return strings.Join([]string{
		"<p align=\"center\">",
		fmt.Sprintf("  <img src=\"%s\" alt=\"%s\" width=\"100%%\" />", heroPath, alt),
		"</p>",
		"",
	}, "\n")
}

func renderLanguageLinks(prefix string) string {
	links := []string{
		fmt.Sprintf("[English](%s%s)", prefix, readmePath("en")),
		fmt.Sprintf("[한국어](%s%s)", prefix, readmePath("ko")),
		fmt.Sprintf("[日本語](%s%s)", prefix, readmePath("ja")),
		fmt.Sprintf("[中文](%s%s)", prefix, readmePath("zh")),
	}
	return strings.Join(links, " | ")
}

func renderRootLinkBar() string {
	return fmt.Sprintf("[Latest Release](%s/releases/latest) | [CI](%s/actions/workflows/ci.yml) | [Security](SECURITY.md)", nambaRepositoryURL, nambaRepositoryURL)
}

func guideFilename(base, lang string) string {
	lang = normalizeReadmeLanguage(lang)
	if lang == "en" {
		return fmt.Sprintf("%s.md", base)
	}
	return fmt.Sprintf("%s.%s.md", base, lang)
}

func localizeGuideLabel(lang, guide string) string {
	lang = normalizeReadmeLanguage(lang)
	switch guide {
	case "workflow-guide":
		switch lang {
		case "ko":
			return "워크플로 가이드"
		case "ja":
			return "ワークフローガイド"
		case "zh":
			return "工作流指南"
		default:
			return "Workflow Guide"
		}
	default:
		switch lang {
		case "ko":
			return "시작 가이드"
		case "ja":
			return "スタートガイド"
		case "zh":
			return "上手指南"
		default:
			return "Getting Started"
		}
	}
}

func renderDocLinkBar(lang string) string {
	return strings.Join([]string{
		fmt.Sprintf("[%s](./%s)", localizeGuideLabel(lang, "getting-started"), guideFilename("getting-started", lang)),
		fmt.Sprintf("[%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
		"[Codex Upstream Reference](./codex-upstream-reference.md)",
	}, " | ")
}

func renderNambaCLIRootLifecycleSection(lang string) []string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return []string{
			"## 설치, 업데이트, 제거",
			"",
			fmt.Sprintf("- 설치 (Windows): `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- 설치 (macOS / Linux): `%s`", nambaInstallShell),
			"- 최신 릴리스로 업데이트: `namba update`",
			"- 특정 릴리스로 고정: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- 제거 (Windows): 기본 경로 `%s`를 삭제하고, 더 이상 쓰지 않으면 `%s`를 사용자 `PATH`에서 제거합니다.", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- 제거 (macOS / Linux): 기본 경로 `%s`를 삭제하고, 더 이상 쓰지 않으면 설치기가 추가한 `PATH` 줄을 `~/.profile` 또는 `~/.zshrc`에서 제거합니다.", nambaUnixBinaryPath),
			"",
		}
	case "ja":
		return []string{
			"## インストール、更新、アンインストール",
			"",
			fmt.Sprintf("- Windows へのインストール: `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- macOS / Linux へのインストール: `%s`", nambaInstallShell),
			"- 最新リリースに更新: `namba update`",
			"- 特定リリースに固定: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- Windows でアンインストール: 既定の `%s` を削除し、不要なら `%s` をユーザー `PATH` から外します。", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- macOS / Linux でアンインストール: 既定の `%s` を削除し、不要ならインストーラが追加した `PATH` 行を `~/.profile` または `~/.zshrc` から削除します。", nambaUnixBinaryPath),
			"",
		}
	case "zh":
		return []string{
			"## 安装、更新与卸载",
			"",
			fmt.Sprintf("- 在 Windows 上安装: `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- 在 macOS / Linux 上安装: `%s`", nambaInstallShell),
			"- 更新到最新发布版: `namba update`",
			"- 固定到指定发布版: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- 在 Windows 上卸载: 删除默认路径 `%s`，如果不再需要，再把 `%s` 从用户 `PATH` 中移除。", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- 在 macOS / Linux 上卸载: 删除默认路径 `%s`，如果不再需要，再从 `~/.profile` 或 `~/.zshrc` 中删除安装器追加的 `PATH` 行。", nambaUnixBinaryPath),
			"",
		}
	default:
		return []string{
			"## Install, Update, and Uninstall",
			"",
			fmt.Sprintf("- Install on Windows: `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- Install on macOS / Linux: `%s`", nambaInstallShell),
			"- Update to the latest release: `namba update`",
			"- Pin a specific release: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- Uninstall on Windows: remove `%s`, then remove `%s` from your user `PATH` if you no longer need it.", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- Uninstall on macOS / Linux: remove `%s`, then delete the `PATH` line that the installer added to `~/.profile` or `~/.zshrc` if you no longer need it.", nambaUnixBinaryPath),
			"",
		}
	}
}

func renderNambaCLIUpdateGuideSection(lang string) []string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return []string{
			"## 2. 업데이트",
			"",
			"- 최신 릴리스: `namba update`",
			"- 특정 릴리스: `namba update --version vX.Y.Z`",
			"- 업데이트한 바이너리가 바로 잡히지 않으면 새 터미널을 열어 경로를 다시 로드합니다.",
			"",
		}
	case "ja":
		return []string{
			"## 2. 更新",
			"",
			"- 最新リリース: `namba update`",
			"- 特定リリース: `namba update --version vX.Y.Z`",
			"- 更新したバイナリがすぐ反映されない場合は、新しいターミナルを開いて `PATH` を再読み込みします。",
			"",
		}
	case "zh":
		return []string{
			"## 2. 更新",
			"",
			"- 最新发布版: `namba update`",
			"- 指定发布版: `namba update --version vX.Y.Z`",
			"- 如果更新后的二进制没有立刻生效，请重新打开终端以重新加载 `PATH`。",
			"",
		}
	default:
		return []string{
			"## 2. Update",
			"",
			"- Latest release: `namba update`",
			"- Specific release: `namba update --version vX.Y.Z`",
			"- Re-open the terminal if the updated binary is not picked up immediately.",
			"",
		}
	}
}

func renderNambaCLIUninstallGuideSection(lang string) []string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return []string{
			"## 3. 제거",
			"",
			fmt.Sprintf("- Windows 기본 경로: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux 기본 경로: `%s`", nambaUnixBinaryPath),
			"- `NAMBA_INSTALL_DIR`로 사용자 지정 경로에 설치했다면 그 위치의 바이너리를 제거합니다.",
			"- 더 이상 쓰지 않으면 해당 경로를 `PATH`에서도 제거합니다.",
			"",
		}
	case "ja":
		return []string{
			"## 3. アンインストール",
			"",
			fmt.Sprintf("- Windows の既定パス: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux の既定パス: `%s`", nambaUnixBinaryPath),
			"- `NAMBA_INSTALL_DIR` で別の場所に入れた場合は、そのパスのバイナリを削除します。",
			"- 不要になったら同じパスを `PATH` からも外します。",
			"",
		}
	case "zh":
		return []string{
			"## 3. 卸载",
			"",
			fmt.Sprintf("- Windows 默认路径: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux 默认路径: `%s`", nambaUnixBinaryPath),
			"- 如果通过 `NAMBA_INSTALL_DIR` 安装到了自定义目录，请删除那个位置的二进制。",
			"- 不再需要时，也要把相同路径从 `PATH` 中移除。",
			"",
		}
	default:
		return []string{
			"## 3. Uninstall",
			"",
			fmt.Sprintf("- Windows default path: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux default path: `%s`", nambaUnixBinaryPath),
			"- If you installed with `NAMBA_INSTALL_DIR`, remove the binary from that custom location instead.",
			"- Remove the matching `PATH` entry when you no longer need it.",
			"",
		}
	}
}

func renderNambaCLIRoot(lang string, cfg docsConfig) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"Codex 네이티브 방식으로 저장소를 초기화하고, 작업을 SPEC 단위로 계획하고, 구현 이후 산출물까지 정리하는 개발 워크플로입니다.",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## 사용자는 무엇을 할 수 있나",
			"",
			"- 빈 디렉터리에서 `namba init .`로 Codex-ready 저장소를 바로 시작할 수 있습니다.",
			"- `namba plan`, `namba fix`로 요청을 SPEC 패키지로 정리하고 작업 범위를 유지할 수 있습니다.",
			"- `namba run SPEC-XXX`와 `namba sync`로 구현, 검증, PR 준비 산출물을 한 흐름으로 마무리할 수 있습니다.",
			"- `namba update`와 릴리스 기반 배포 흐름으로 팀 전체 CLI 버전을 맞출 수 있습니다.",
			"",
			"## 빠른 시작",
			"",
			"### 1. NambaAI 설치",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 새 저장소 초기화",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Codex에서 작업 시작",
			"",
			"```text",
			"namba project",
			"namba plan \"로그인 감사 로그 추가\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"로그인 감사 로그 추가\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Codex 안의 Command Skill",
			"",
			"- `$namba`: Codex가 적절한 Namba 진입점을 고르도록 맡기는 일반 라우터입니다.",
			"- `$namba-project`: 작업 전후에 프로젝트 문서와 codemap을 새로 고칩니다.",
			"- `$namba-plan` / `$namba-fix`: 다음 feature 또는 bugfix SPEC 패키지를 만듭니다.",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: SPEC용 product, engineering, design review 산출물과 readiness 요약을 갱신합니다.",
			"- `$namba-run`: 현재 Codex 세션에서 SPEC 패키지를 Namba 워크플로로 실행합니다.",
			"- `$namba-sync`: README 번들, 프로젝트 문서, codemap, PR 준비 산출물을 갱신합니다.",
			"- `$namba-pr` / `$namba-land`: 현재 브랜치를 GitHub 리뷰로 넘기고, 체크가 끝나면 안전하게 머지합니다.",
			"- `$namba-regen` / `$namba-update`: repo-local Codex 자산을 다시 생성하거나 설치된 `namba` CLI를 self-update 합니다.",
			"",
			"## Skill 에서 Command 로 매핑",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Codex Custom Agents",
			"",
			"- Strategy: `namba-product-manager`는 범위와 acceptance를 다듬고, `namba-planner`는 SPEC를 실행 계획으로 바꿉니다.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, `namba-designer`가 웹 UI, 모바일 실행, 시각 방향을 맡습니다.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, `namba-data-engineer`가 API, 저장소, 마이그레이션, 파이프라인을 맡습니다.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, `namba-reviewer`가 보안, 회귀 신뢰도, CI/CD, 최종 검수를 맡습니다.",
			"- General delivery: `namba-implementer`는 여러 도메인이 섞였지만 큰 specialist 팀까지는 필요 없는 작업을 맡는 일반 실행 에이전트입니다.",
			"",
			"## 더 자세히 보기",
			"",
			fmt.Sprintf("- [%s](%s): 설치, 업데이트, 제거, 초기화, 첫 실행 흐름", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync 차이, 산출물, 협업 규칙", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): 이 저장소가 맞추는 Codex 기준",
			"- [SECURITY.md](SECURITY.md): 보안 정책",
			"",
			"## 기술 요약",
			"",
			"- `.namba/`는 설정, SPEC, 프로젝트 문서의 source of truth입니다.",
			"- `.agents/skills/`는 Codex가 읽는 repo-local skill surface입니다.",
			"- `.codex/agents/*.toml`은 product, planning, design, frontend, mobile, backend, data, security, testing, ops, implementation, review용 task-oriented custom agent를 정의합니다.",
			"- `namba update`, `namba regen`, `namba sync`, `namba pr`, `namba land`는 서로 다른 문제를 해결하며 섞어 쓰면 안 됩니다.",
			"",
		)
		return strings.Join(lines, "\n")
	case "ja":
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI は、Codex ネイティブでリポジトリを初期化し、作業を SPEC 単位で計画し、実装後の成果物まで同期する開発ワークフローです。",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## NambaAI でできること",
			"",
			"- 空のディレクトリで `namba init .` を実行し、Codex-ready なリポジトリをすぐに開始できます。",
			"- `namba plan` と `namba fix` で依頼を SPEC パッケージに整理し、作業範囲を安定させられます。",
			"- `namba run SPEC-XXX` と `namba sync` で実装、検証、PR 準備を一連の流れで完了できます。",
			"- `namba update` とリリース配布で、チーム全体の CLI バージョンを揃えられます。",
			"",
			"## クイックスタート",
			"",
			"### 1. NambaAI をインストール",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 新しいリポジトリを初期化",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Codex で作業を開始",
			"",
			"```text",
			"namba project",
			"namba plan \"ログイン監査ログを追加\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"ログイン監査ログを追加\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Codex の Command Skill",
			"",
			"- `$namba`: Codex に適切な Namba の入口を選ばせるための汎用ルータです。",
			"- `$namba-project`: 作業の前後でプロジェクト文書と codemap を更新します。",
			"- `$namba-plan` / `$namba-fix`: 次の feature または bugfix SPEC パッケージを作ります。",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: SPEC 用の product / engineering / design review 成果物と readiness 要約を更新します。",
			"- `$namba-run`: 現在の Codex セッションで SPEC パッケージを Namba ワークフローとして実行します。",
			"- `$namba-sync`: README バンドル、プロジェクト文書、codemap、PR 準備物を更新します。",
			"- `$namba-pr` / `$namba-land`: 現在のブランチを GitHub レビューに渡し、チェック完了後に安全にマージします。",
			"- `$namba-regen` / `$namba-update`: repo-local Codex 資産を再生成するか、インストール済み `namba` CLI を self-update します。",
			"",
			"## Skill から Command への対応",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Codex Custom Agents",
			"",
			"- Strategy: `namba-product-manager` がスコープと acceptance を整え、`namba-planner` が SPEC を実行計画に変えます。",
			"- UI and experience: `namba-frontend-architect`、`namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer` が Web UI、モバイル実装、ビジュアル方向を担当します。",
			"- Backend and data: `namba-backend-architect`、`namba-backend-implementer`、`namba-data-engineer` が API、永続化、マイグレーション、パイプラインを担当します。",
			"- Security and delivery: `namba-security-engineer`、`namba-test-engineer`、`namba-devops-engineer`、`namba-reviewer` が hardening、回帰信頼性、CI/CD、最終受け入れを担当します。",
			"- General delivery: `namba-implementer` は複数ドメインにまたがるが大きな specialist チームまでは不要な作業を担う汎用実装エージェントです。",
			"",
			"## さらに詳しく",
			"",
			fmt.Sprintf("- [%s](%s): インストール、更新、アンインストール、初期化、最初の実行", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync の違い、成果物、協業ルール", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): このリポジトリが合わせている Codex の基準",
			"- [SECURITY.md](SECURITY.md): セキュリティポリシー",
			"",
			"## 技術スナップショット",
			"",
			"- `.namba/` は設定、SPEC、プロジェクト文書の source of truth です。",
			"- `.agents/skills/` は Codex が読む repo-local skill surface です。",
			"- `.codex/agents/*.toml` は product、planning、design、frontend、mobile、backend、data、security、testing、ops、implementation、review をまたぐ task-oriented custom agent を定義します。",
			"- `namba update`、`namba regen`、`namba sync`、`namba pr`、`namba land` は別の問題を解くので混同しません。",
			"",
		)
		return strings.Join(lines, "\n")
	case "zh":
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI 是一套面向 Codex 的开发工作流，用来初始化仓库、以 SPEC 形式规划工作，并在实现后同步项目产物。",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## 你可以用 NambaAI 做什么",
			"",
			"- 在空目录中执行 `namba init .`，快速得到可直接用于 Codex 的仓库。",
			"- 用 `namba plan` 和 `namba fix` 把需求整理成 SPEC 包，保持范围清晰。",
			"- 用 `namba run SPEC-XXX` 和 `namba sync` 完成实现、校验与 PR 准备。",
			"- 通过 `namba update` 和发布资产，让团队统一 CLI 版本。",
			"",
			"## 快速开始",
			"",
			"### 1. 安装 NambaAI",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 初始化一个新仓库",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. 在 Codex 中开始工作",
			"",
			"```text",
			"namba project",
			"namba plan \"添加登录审计日志\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"添加登录审计日志\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Codex 中的 Command Skill",
			"",
			"- `$namba`: 通用路由入口，让 Codex 选择合适的 Namba 工作流命令。",
			"- `$namba-project`: 在开始前或较大改动后刷新项目文档与 codemap。",
			"- `$namba-plan` / `$namba-fix`: 创建下一个 feature 或 bugfix SPEC 包。",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: 更新 SPEC 的 product / engineering / design review 产物与 readiness 摘要。",
			"- `$namba-run`: 在当前 Codex 会话中按 Namba 工作流执行 SPEC 包。",
			"- `$namba-sync`: 刷新 README bundle、项目文档、codemap 与 PR 准备产物。",
			"- `$namba-pr` / `$namba-land`: 把当前分支交给 GitHub review，并在检查通过后安全合并。",
			"- `$namba-regen` / `$namba-update`: 重新生成 repo-local Codex 资产，或 self-update 已安装的 `namba` CLI。",
			"",
			"## Skill 到 Command 的映射",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Codex Custom Agents",
			"",
			"- Strategy: `namba-product-manager` 负责收敛范围与 acceptance，`namba-planner` 把 SPEC 转成执行计划。",
			"- UI and experience: `namba-frontend-architect`、`namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer` 负责 Web UI、移动端实现与视觉方向。",
			"- Backend and data: `namba-backend-architect`、`namba-backend-implementer`、`namba-data-engineer` 负责 API、持久化、迁移与数据管道。",
			"- Security and delivery: `namba-security-engineer`、`namba-test-engineer`、`namba-devops-engineer`、`namba-reviewer` 负责加固、回归信心、CI/CD 与最终验收。",
			"- General delivery: `namba-implementer` 负责跨多个领域但还不需要大规模 specialist 团队的通用执行工作。",
			"",
			"## 进一步了解",
			"",
			fmt.Sprintf("- [%s](%s): 安装、更新、卸载、初始化与首次运行", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync 的区别、产物与协作规则", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): 本仓库遵循的 Codex 参考",
			"- [SECURITY.md](SECURITY.md): 安全策略",
			"",
			"## 技术概览",
			"",
			"- `.namba/` 是配置、SPEC 和项目文档的 source of truth。",
			"- `.agents/skills/` 是 Codex 实际读取的 repo-local skill surface。",
			"- `.codex/agents/*.toml` 定义了覆盖 product、planning、design、frontend、mobile、backend、data、security、testing、ops、implementation、review 的 task-oriented custom agent。",
			"- `namba update`、`namba regen`、`namba sync`、`namba pr`、`namba land` 各自解决不同问题，不能混用。",
			"",
		)
		return strings.Join(lines, "\n")
	default:
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI is a Codex-native workflow for bootstrapping repositories, planning work as SPEC packages, and syncing project artifacts after implementation.",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## What You Can Do With NambaAI",
			"",
			"- Bootstrap a Codex-ready repository from an empty directory with `namba init .`.",
			"- Turn change requests into SPEC packages with `namba plan` and `namba fix`.",
			"- Execute work with `namba run SPEC-XXX` for the default flow, use `--solo` or `--team` for standalone subagent-oriented runs, or `--parallel` for worktree fan-out before handing off with `namba sync`, `namba pr`, and `namba land`.",
			"- Run explicit plan reviews with `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` when a SPEC needs product, engineering, or design critique before implementation.",
			"- Keep CLI versions aligned across the team with `namba update` and release assets.",
			"",
			"## Quick Start",
			"",
			"### 1. Install NambaAI",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. Bootstrap a new repository",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Start working from Codex",
			"",
			"```text",
			"namba project",
			"namba plan \"add login audit logs\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add login audit logs\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Command Skills In Codex",
			"",
			"- `$namba`: general router when you want Codex to choose the right Namba workflow entry point.",
			"- `$namba-project`: refresh project docs and codemaps before starting or after larger changes.",
			"- `$namba-plan` / `$namba-fix`: create the next feature or bugfix SPEC package.",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: update product, engineering, or design review artifacts plus the advisory readiness summary for a SPEC.",
			"- `$namba-run`: execute a SPEC package through the Namba workflow in the current Codex session.",
			"- `$namba-sync`: refresh README bundles, project docs, codemaps, and PR-ready artifacts.",
			"- `$namba-pr` / `$namba-land`: hand off the current branch for GitHub review, then merge it safely after checks pass.",
			"- `$namba-regen` / `$namba-update`: regenerate repo-local Codex assets or self-update the installed `namba` CLI.",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Custom Agents In Codex",
			"",
			"- Strategy: `namba-product-manager` shapes scope and acceptance, and `namba-planner` turns a SPEC into an execution plan.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, and `namba-designer` cover web UI, mobile execution, and visual direction.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, and `namba-data-engineer` cover APIs, persistence, migrations, and pipelines.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, and `namba-reviewer` cover hardening, regression confidence, CI/CD, and final acceptance.",
			"- General delivery: `namba-implementer` remains the generalist execution agent when a task spans multiple domains but does not justify a larger specialist team.",
			"",
			"## Need More Detail?",
			"",
			fmt.Sprintf("- [%s](%s): installation, updates, uninstall, init, and first-run flow", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update vs regen vs sync vs pr vs land, run modes, generated assets, and collaboration defaults", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): upstream baseline this repository follows",
			"- [SECURITY.md](SECURITY.md): security policy",
			"",
			"## Technical Snapshot",
			"",
			"- `.namba/` is the source of truth for config, SPEC packages, and project docs.",
			"- `.agents/skills/` is the repo-local skill surface used by Codex.",
			"- `.codex/agents/*.toml` defines task-oriented custom agents across product, planning, design, frontend, mobile, backend, data, security, testing, ops, implementation, and review.",
			"- `namba update`, `namba regen`, `namba sync`, `namba pr`, and `namba land` solve different problems and should not be mixed.",
			"",
		)
		return strings.Join(lines, "\n")
	}
}

func renderManagedProjectRoot(lang string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	title := projectCfg.Name
	if title == "" {
		title = "Project"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"NambaAI가 관리하는 Codex 네이티브 작업 저장소입니다. 이 README는 저장소를 처음 여는 사람이 바로 작업 흐름을 이해하도록 `namba sync`가 생성합니다.",
			"",
			renderLanguageLinks(""),
			"",
			"## 이 저장소에서 할 수 있는 일",
			"",
			"- `namba project`로 현재 프로젝트 구조와 핵심 문서를 새로 읽을 수 있습니다.",
			"- `namba plan` 또는 `namba fix`로 요청을 SPEC 패키지로 정리할 수 있습니다.",
			"- `namba run SPEC-XXX`로 구현을 진행하고 검증을 거친 뒤 `namba sync`로 산출물을 정리할 수 있습니다.",
			"- 브랜치, PR, Codex 리뷰 흐름을 같은 규칙으로 유지할 수 있습니다.",
			"",
			"## 빠르게 시작하기",
			"",
			"```text",
			"namba project",
			"namba plan \"작업 설명\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 더 보기",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 현재 기본 규칙",
			"",
			fmt.Sprintf("- 작업 언어: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR 대상 브랜치: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex 리뷰 코멘트: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"このリポジトリは NambaAI で管理されています。初めて開いた人が作業フローをすぐ理解できるように、この README は `namba sync` によって生成されます。",
			"",
			renderLanguageLinks(""),
			"",
			"## このリポジトリでできること",
			"",
			"- `namba project` で現在の構成と主要ドキュメントを更新できます。",
			"- `namba plan` または `namba fix` で依頼を SPEC パッケージに整理できます。",
			"- `namba run SPEC-XXX` で実装を進め、検証後に `namba sync` で成果物を整理できます。",
			"- ブランチ、PR、Codex レビューの流れを同じルールで維持できます。",
			"",
			"## すぐ始める",
			"",
			"```text",
			"namba project",
			"namba plan \"作業内容\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## さらに読む",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 現在の既定値",
			"",
			fmt.Sprintf("- 作業言語: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR ベースブランチ: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex レビューコメント: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"这个仓库由 NambaAI 管理。为了让第一次打开仓库的人快速理解工作流，这份 README 会由 `namba sync` 生成。",
			"",
			renderLanguageLinks(""),
			"",
			"## 你可以在这个仓库里做什么",
			"",
			"- 用 `namba project` 刷新当前项目结构和核心文档。",
			"- 用 `namba plan` 或 `namba fix` 把需求整理成 SPEC 包。",
			"- 用 `namba run SPEC-XXX` 执行实现，并在校验后用 `namba sync` 整理产物。",
			"- 用统一规则维护分支、PR 和 Codex 评审流程。",
			"",
			"## 快速开始",
			"",
			"```text",
			"namba project",
			"namba plan \"工作说明\"",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 继续阅读",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 当前默认值",
			"",
			fmt.Sprintf("- 工作语言: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR 基准分支: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex 评审评论: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"This repository is managed with NambaAI. The README is generated by `namba sync` so contributors can understand the workflow before they touch the code.",
			"",
			renderLanguageLinks(""),
			"",
			"## What You Can Do In This Repository",
			"",
			"- Run `namba project` to refresh the current structure and core docs.",
			"- Use `namba plan` or `namba fix` to package requests as SPEC work.",
			"- Use `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` when a SPEC needs explicit pre-implementation review depth.",
			"- Execute `namba run SPEC-XXX` for the default flow, or use `--solo`, `--team`, and `--parallel` when the task needs single-specialist, small-team, or worktree fan-out execution.",
			"- Keep branch, PR, and Codex review flow consistent across contributors.",
			"",
			"## Start Fast",
			"",
			"```text",
			"namba project",
			"namba plan \"work description\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
			"## Command Skills In Codex",
			"",
			"- `$namba`: general router when you want Codex to choose the right Namba entry point.",
			"- `$namba-project`: refresh docs and codemaps before implementation or after larger changes.",
			"- `$namba-plan` / `$namba-fix`: create the next feature or bug-fix SPEC package.",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: update product, engineering, or design review artifacts plus the advisory readiness summary for a SPEC.",
			"- `$namba-run`: execute the current SPEC package with the Namba run workflow.",
			"- `$namba-sync`: refresh README bundles, project docs, codemaps, and PR-ready artifacts.",
			"- `$namba-pr` / `$namba-land`: prepare GitHub review handoff, then merge safely after checks pass.",
			"- `$namba-regen` / `$namba-update`: regenerate repo-local Codex assets or update the installed `namba` CLI.",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Custom Agents In Codex",
			"",
			"- Strategy: `namba-product-manager` shapes scope and acceptance, and `namba-planner` turns a SPEC into an execution plan.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, and `namba-designer` cover web UI, mobile execution, and visual direction.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, and `namba-data-engineer` cover APIs, persistence, migrations, and pipelines.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, and `namba-reviewer` cover hardening, regression confidence, CI/CD, and final acceptance.",
			"- General delivery: `namba-implementer` remains available when a task spans multiple domains but does not justify a larger specialist roster.",
			"",
			"## Read More",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## Current Defaults",
			"",
			fmt.Sprintf("- Working language: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR base branch: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex review comment: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	}
}

func renderNambaCLIGuide(lang, guide string) string {
	switch guide {
	case "workflow-guide":
		return renderNambaCLIWorkflowGuide(lang)
	default:
		return renderNambaCLIGettingStarted(lang)
	}
}

func renderManagedProjectGuide(lang, guide string, projectCfg projectConfig, profile initProfile) string {
	switch guide {
	case "workflow-guide":
		return renderManagedProjectWorkflowGuide(lang, projectCfg, profile)
	default:
		return renderManagedProjectGettingStarted(lang, projectCfg)
	}
}

func renderNambaCLIGettingStarted(lang string) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 설치",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- 저장소 안에서 작업할 때 Windows의 Codex CLI 경험을 가장 안정적으로 쓰려면 WSL 워크스페이스를 권장합니다.",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- 기본 경로 대신 다른 곳에 설치하려면 `NAMBA_INSTALL_DIR`를 사용합니다.",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. 새 저장소 초기화",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard에서는 작업 언어, approval_policy, sandbox_mode, PR 언어, Codex agent mode를 함께 고를 수 있습니다.",
			"",
			"## 5. Codex에서 기본 흐름 실행",
			"",
			"```text",
			"namba project",
			"namba plan \"대시보드 필터 추가\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"대시보드 필터 추가\"",
			"namba land",
			"```",
			"",
			"## 6. 다음에 보면 좋은 문서",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	case "ja":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. インストール",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- リポジトリ内で作業する Windows の Codex CLI 体験は、WSL ワークスペースの方が安定します。",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- 既定の場所ではなく別の場所に入れたい場合は `NAMBA_INSTALL_DIR` を使います。",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. 新しいリポジトリを初期化",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard では作業言語、approval_policy、sandbox_mode、PR 言語、Codex agent mode をまとめて選べます。",
			"",
			"## 5. Codex で基本フローを実行",
			"",
			"```text",
			"namba project",
			"namba plan \"ダッシュボードフィルタを追加\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"ダッシュボードフィルタを追加\"",
			"namba land",
			"```",
			"",
			"## 6. 次に読む文書",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	case "zh":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 安装",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- 如果你在仓库里使用 Windows 版 Codex CLI，WSL 工作区通常会更稳定。",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- 如果要安装到默认路径之外的位置，请使用 `NAMBA_INSTALL_DIR`。",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. 初始化新仓库",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard 中可以一起选择工作语言、approval_policy、sandbox_mode、PR 语言和 Codex agent mode。",
			"",
			"## 5. 在 Codex 中执行基本流程",
			"",
			"```text",
			"namba project",
			"namba plan \"添加仪表盘筛选\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"添加仪表盘筛选\"",
			"namba land",
			"```",
			"",
			"## 6. 下一步建议阅读",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	default:
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. Install",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- For the best Codex CLI experience on Windows, use a WSL workspace when you work inside a repository.",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- Use `NAMBA_INSTALL_DIR` when you want a non-default install location.",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. Bootstrap a new repository",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"The wizard aligns working language, approval_policy, sandbox_mode, PR language, and Codex agent mode.",
			"",
			"## 5. Run the basic Codex flow",
			"",
			"```text",
			"namba project",
			"namba plan \"add dashboard filters\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add dashboard filters\"",
			"namba land",
			"```",
			"",
			"## 6. Read next",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	}
}

func renderNambaCLIWorkflowGuide(lang string) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`, `regen`, `sync`, `pr`, `land`는 다른 명령입니다",
			"",
			"- `namba update`: 설치된 `namba` CLI를 GitHub Release 기준으로 self-update",
			"- `namba regen`: AGENTS, skills, custom agents, repo Codex config 같은 template-generated 자산 재생성",
			"- `namba sync`: README, 프로젝트 문서, codemap, advisory review readiness, PR 체크리스트, 릴리스 메모 갱신",
			"- `namba pr`: 기본으로 sync와 validation을 실행하고, 현재 브랜치를 commit/push 한 뒤 PR을 열거나 재사용하며 Codex review marker까지 맞춥니다.",
			"- `namba land`: 필요하면 체크를 기다리고, PR이 깨끗할 때만 머지한 뒤 로컬 `main`을 안전하게 갱신합니다.",
			"",
			"## `namba run` 모드",
			"",
			"- `namba run SPEC-XXX`: 한 작업공간에서 실행하는 기본 standalone Codex 흐름입니다.",
			"- `namba run SPEC-XXX --solo`: 한 작업공간 안에서 단일 specialist subagent 흐름으로 실행합니다.",
			"- `namba run SPEC-XXX --team`: 한 작업공간 안에서 소규모 multi-subagent 흐름으로 실행합니다.",
			"- `namba run SPEC-XXX --parallel`: Codex subagent orchestration이 아니라 Namba가 관리하는 git worktree fan-out/fan-in입니다.",
			"",
			"## 역할 라우팅",
			"",
			"- 기본 `namba run`은 프롬프트에 강한 specialist 신호가 없으면 standalone runner에 머뭅니다.",
			"- `--solo`는 한 도메인이 분명할 때 specialist 1명만 쓰고, `--team`은 acceptance가 여러 도메인에 걸칠 때만 specialist 둘과 reviewer까지 확장합니다.",
			"- UI, responsive, mobile, design 작업은 `namba-frontend-implementer`, `namba-mobile-engineer`, `namba-designer`로 보내고, API, schema, pipeline 작업은 `namba-backend-implementer`, `namba-data-engineer`로 보냅니다. auth, secrets, compliance는 `namba-security-engineer`, deployment와 runtime은 `namba-devops-engineer`가 맡습니다.",
			"- Standalone runner는 integrator이자 validation owner로 유지하고, 통제되지 않은 swarm 대신 최종 acceptance는 `namba-reviewer`로 점검합니다.",
			"",
			"## 리뷰 준비도",
			"",
			"- `namba plan`과 `namba fix`는 `.namba/specs/<SPEC>/reviews/product.md`, `engineering.md`, `design.md`, `readiness.md`를 seed 합니다.",
			"- 구현 전이나 PR handoff 전에 `$namba-plan-pm-review`, `$namba-plan-eng-review`, `$namba-plan-design-review`로 review 산출물을 최신 상태로 유지합니다.",
			"- 누락된 review pass는 기본으로 advisory 상태입니다. `namba run`, `namba sync`, `namba pr`는 현재 readiness 요약을 보여주지만 조용히 하드블록하지 않습니다.",
			"",
			"## 주요 생성 산출물",
			"",
			"- `.namba/`: 설정, SPEC, project docs, logs",
			"- `.namba/specs/<SPEC>/reviews/`: SPEC별 advisory product, engineering, design, readiness artifact",
			"- `.agents/skills/`: Codex가 직접 읽는 repo-local skills",
			"- `.codex/config.toml`: repo-local Codex 기본값과 Namba가 관리하는 MCP preset",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary, release notes, checklist, codemap",
			"",
			"## 협업 기본값",
			"",
			"- 작업은 전용 브랜치에서 진행합니다.",
			"- `namba pr`는 `main`을 대상으로 하고, 설정된 PR 언어와 review marker를 함께 맞춥니다.",
			"- `namba land`는 깨끗한 PR만 머지하고 로컬 `main`을 다른 작업을 덮지 않게 갱신합니다.",
			"- GitHub review 요청은 `@codex review`를 사용합니다.",
			"",
			"## 릴리스 흐름",
			"",
			"- `namba release`는 `main`의 clean working tree를 요구합니다.",
			"- `--push`는 새 tag와 `main`을 함께 push 한 뒤 GitHub Release workflow를 트리거합니다.",
			"",
		}
		return strings.Join(lines, "\n")
	case "ja":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`、`regen`、`sync`、`pr`、`land` は別のコマンドです",
			"",
			"- `namba update`: インストール済み CLI を GitHub Release ベースで self-update",
			"- `namba regen`: AGENTS、skills、custom agents、repo Codex config などの template-generated assets を再生成",
			"- `namba sync`: README、プロジェクト文書、codemap、advisory review readiness、PR checklist、release notes を更新",
			"- `namba pr`: 既定で sync と validation を実行し、現在のブランチを commit/push して PR を開くか再利用し、Codex review marker まで整えます。",
			"- `namba land`: 必要ならチェック完了を待ち、PR が clean なときだけマージし、ローカル `main` を安全に更新します。",
			"",
			"## `namba run` モード",
			"",
			"- `namba run SPEC-XXX`: 1 つのワークスペースで進める標準の standalone Codex フローです。",
			"- `namba run SPEC-XXX --solo`: 1 つのワークスペース内で単一 specialist subagent フローを実行します。",
			"- `namba run SPEC-XXX --team`: 1 つのワークスペース内で小規模な multi-subagent フローを実行します。",
			"- `namba run SPEC-XXX --parallel`: Codex subagent orchestration ではなく、Namba 管理の git worktree fan-out/fan-in です。",
			"",
			"## 役割ルーティング",
			"",
			"- 既定の `namba run` は、プロンプトに強い specialist シグナルがない限り standalone runner のままです。",
			"- `--solo` は 1 つのドメインが明確なときだけ specialist を 1 人使い、`--team` は acceptance が複数ドメインにまたがるときだけ specialist 2 人と reviewer まで広げます。",
			"- UI、responsive、mobile、design の作業は `namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer` に、API、schema、pipeline は `namba-backend-implementer`、`namba-data-engineer` に回します。auth、secrets、compliance は `namba-security-engineer`、deployment と runtime は `namba-devops-engineer` が担当します。",
			"- Standalone runner は integrator 兼 validation owner として維持し、制御できない swarm ではなく最終 acceptance は `namba-reviewer` で確認します。",
			"",
			"## レビュー準備度",
			"",
			"- `namba plan` と `namba fix` は `.namba/specs/<SPEC>/reviews/product.md`、`engineering.md`、`design.md`、`readiness.md` を seed します。",
			"- 実装前や PR handoff 前に `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` を使って review 成果物を最新に保ちます。",
			"- 足りない review pass は既定で advisory のままです。`namba run`、`namba sync`、`namba pr` は現在の readiness 要約を見せますが、黙って delivery を hard-block しません。",
			"",
			"## 主要な生成アセット",
			"",
			"- `.namba/`: config, specs, project docs, logs",
			"- `.namba/specs/<SPEC>/reviews/`: SPEC ごとの advisory product / engineering / design / readiness artifacts",
			"- `.agents/skills/`: Codex が直接読む repo-local skills",
			"- `.codex/config.toml`: repo-local Codex defaults と Namba 管理 MCP preset",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary、release notes、checklist、codemap",
			"",
			"## 協業の既定値",
			"",
			"- 作業は専用ブランチで進めます。",
			"- `namba pr` は `main` を対象にし、設定済み PR 言語と review marker を揃えます。",
			"- `namba land` は clean な PR だけをマージし、ローカル `main` を他の作業を壊さず更新します。",
			"- GitHub review 依頼には `@codex review` を使います。",
			"",
			"## リリースフロー",
			"",
			"- `namba release` は `main` 上の clean working tree を要求します。",
			"- `--push` は新しい tag と `main` を一緒に push し、その後 GitHub Release workflow を起動します。",
			"",
		}
		return strings.Join(lines, "\n")
	case "zh":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`、`regen`、`sync`、`pr`、`land` 是不同命令",
			"",
			"- `namba update`: 按 GitHub Release 更新已安装的 CLI",
			"- `namba regen`: 重新生成 AGENTS、skills、custom agents、repo Codex config 等模板产物",
			"- `namba sync`: 刷新 README、项目文档、codemap、advisory review readiness、PR checklist、release notes",
			"- `namba pr`: 默认先执行 sync 与 validation，再把当前分支 commit/push，打开或复用 PR，并确保 Codex review marker 已存在。",
			"- `namba land`: 必要时等待检查完成，只在 PR 干净时合并，并安全更新本地 `main`。",
			"",
			"## `namba run` 模式",
			"",
			"- `namba run SPEC-XXX`: 在一个工作区里执行的标准 standalone Codex 流程。",
			"- `namba run SPEC-XXX --solo`: 在一个工作区内运行单 specialist subagent 流程。",
			"- `namba run SPEC-XXX --team`: 在一个工作区内运行小规模 multi-subagent 流程。",
			"- `namba run SPEC-XXX --parallel`: 这不是 Codex subagent orchestration，而是 Namba 管理的 git worktree fan-out/fan-in。",
			"",
			"## 角色路由",
			"",
			"- 默认 `namba run` 会留在 standalone runner，除非提示里出现很强的 specialist 信号。",
			"- `--solo` 只在单一领域非常明确时使用 1 个 specialist；`--team` 只在 acceptance 跨多个领域时扩展到 2 个 specialist 加 reviewer。",
			"- UI、responsive、mobile、design 工作交给 `namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer`；API、schema、pipeline 交给 `namba-backend-implementer`、`namba-data-engineer`；auth、secrets、compliance 交给 `namba-security-engineer`；deployment 与 runtime 交给 `namba-devops-engineer`。",
			"- Standalone runner 仍是 integrator 和 validation owner；最终 acceptance 由 `namba-reviewer` 把关，而不是放任失控的 swarm。",
			"",
			"## 评审就绪度",
			"",
			"- `namba plan` 和 `namba fix` 会生成 `.namba/specs/<SPEC>/reviews/product.md`、`engineering.md`、`design.md`、`readiness.md`。",
			"- 在实现前或 PR handoff 前，使用 `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` 保持这些 review 产物是最新的。",
			"- 缺失的 review pass 默认仍是 advisory 状态。`namba run`、`namba sync`、`namba pr` 会展示当前 readiness 摘要，但不会悄悄硬阻塞交付。",
			"",
			"## 关键生成资产",
			"",
			"- `.namba/`: config, specs, project docs, logs",
			"- `.namba/specs/<SPEC>/reviews/`: 每个 SPEC 的 advisory product / engineering / design / readiness artifacts",
			"- `.agents/skills/`: Codex 直接读取的 repo-local skills",
			"- `.codex/config.toml`: repo-local Codex defaults 与 Namba 管理的 MCP preset",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary、release notes、checklist、codemap",
			"",
			"## 协作默认值",
			"",
			"- 工作在专用分支中进行。",
			"- `namba pr` 以 `main` 为目标，并保持已配置的 PR 语言与 review marker 一致。",
			"- `namba land` 只合并干净的 PR，并在不覆盖其他工作的前提下更新本地 `main`。",
			"- GitHub review 请求使用 `@codex review`。",
			"",
			"## 发布流程",
			"",
			"- `namba release` 要求 `main` 上有 clean working tree。",
			"- `--push` 会同时推送新 tag 与 `main`，然后触发 GitHub Release workflow。",
			"",
		}
		return strings.Join(lines, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`, `regen`, `sync`, `pr`, and `land` are different commands",
			"",
			"- `namba update`: self-update the installed CLI from GitHub Release assets",
			"- `namba regen`: regenerate AGENTS, skills, custom agents, and repo Codex config",
			"- `namba sync`: refresh README, project docs, codemaps, advisory review readiness, PR checklists, and release notes",
			"- `namba pr`: run sync plus validation by default, commit and push the current branch, open or reuse the PR, and ensure the Codex review marker exists",
			"- `namba land`: optionally wait for checks, merge only when the PR is clean, and update local `main` safely",
			"",
			"## `namba run` modes",
			"",
			"- `namba run SPEC-XXX`: standard standalone Codex flow in one workspace.",
			"- `namba run SPEC-XXX --solo`: standalone single-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --team`: standalone multi-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --parallel`: Namba-managed git worktree fan-out/fan-in, not Codex subagent orchestration.",
			"",
			"## Role routing",
			"",
			"- Default `namba run` stays in the standalone runner unless the prompt shows a strong specialist signal.",
			"- `--solo` uses at most one specialist when one domain clearly dominates; `--team` expands to two specialists plus reviewer only when acceptance spans multiple domains.",
			"- Route UI, responsive, mobile, and design work to `namba-frontend-implementer`, `namba-mobile-engineer`, or `namba-designer`; API, schema, and pipeline work to `namba-backend-implementer` or `namba-data-engineer`; auth, secrets, and compliance work to `namba-security-engineer`; deployment and runtime work to `namba-devops-engineer`.",
			"- Keep the standalone runner as integrator and validation owner; use `namba-reviewer` for the final acceptance pass rather than growing an uncontrolled swarm.",
			"",
			"## Review readiness",
			"",
			"- `namba plan` and `namba fix` seed `.namba/specs/<SPEC>/reviews/product.md`, `engineering.md`, `design.md`, and `readiness.md`.",
			"- Use `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` to keep those artifacts current before implementation or PR handoff.",
			"- Missing review passes stay advisory by default: `namba run`, `namba sync`, and `namba pr` surface the current readiness summary without silently hard-blocking delivery.",
			"",
			"## Key generated assets",
			"",
			"- `.namba/`: config, SPEC packages, project docs, logs",
			"- `.namba/specs/<SPEC>/reviews/`: advisory product, engineering, design, and readiness artifacts for each SPEC",
			"- `.agents/skills/`: repo-local skills used directly by Codex",
			"- `.codex/config.toml`: repo-local Codex defaults plus any configured Namba-managed MCP presets",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary, release notes, checklist, codemap",
			"",
			"## Collaboration defaults",
			"",
			"- Work happens on dedicated branches.",
			"- `namba pr` targets `main` and keeps the configured PR language plus review marker aligned.",
			"- `namba land` merges only clean PRs and updates local `main` without clobbering unrelated work.",
			"- GitHub review requests use `@codex review`.",
			"",
			"## Release flow",
			"",
			"- `namba release` requires a clean working tree on `main`.",
			"- `--push` pushes both the new tag and `main`, then triggers the GitHub Release workflow.",
			"",
		}, "\n")
	}
}

func renderManagedProjectGettingStarted(lang string, projectCfg projectConfig) string {
	projectName := projectCfg.Name
	if projectName == "" {
		projectName = "this repository"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 저장소 열기",
			"",
			fmt.Sprintf("- `%s` 루트에서 Codex를 실행합니다.", projectName),
			"- `namba doctor`로 기본 준비 상태를 확인할 수 있습니다.",
			"",
			"## 2. 현재 컨텍스트 갱신",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 작업 패키지 만들기",
			"",
			"- 기능 작업: `namba plan \"설명\"`",
			"- 버그 수정: `namba fix \"설명\"`",
			"",
			"## 4. 구현과 정리",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. リポジトリを開く",
			"",
			fmt.Sprintf("- `%s` のルートで Codex を起動します。", projectName),
			"- `namba doctor` で準備状態を確認できます。",
			"",
			"## 2. 現在のコンテキストを更新",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 作業パッケージを作る",
			"",
			"- 機能作業: `namba plan \"説明\"`",
			"- バグ修正: `namba fix \"説明\"`",
			"",
			"## 4. 実装と同期",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 打开仓库",
			"",
			fmt.Sprintf("- 在 `%s` 根目录启动 Codex。", projectName),
			"- 可用 `namba doctor` 检查准备状态。",
			"",
			"## 2. 刷新当前上下文",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 创建工作包",
			"",
			"- 功能需求: `namba plan \"说明\"`",
			"- 缺陷修复: `namba fix \"说明\"`",
			"",
			"## 4. 实现并同步",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. Open the repository",
			"",
			fmt.Sprintf("- Start Codex from the root of `%s`.", projectName),
			"- On Windows, prefer a WSL workspace when you want the best Codex CLI behavior inside the repository.",
			"- Run `namba doctor` if you want a quick readiness check.",
			"",
			"## 2. Refresh current context",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. Create a work package",
			"",
			"- Feature request: `namba plan \"description\"`",
			"- Bug fix: `namba fix \"description\"`",
			"",
			"## 4. Review plan readiness",
			"",
			"- Use `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` when a SPEC needs product, engineering, or design critique before coding starts.",
			"- Keep `.namba/specs/<SPEC>/reviews/readiness.md` current so review depth stays visible before `namba run` and `namba pr`.",
			"",
			"## 5. Implement and sync",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 6. Hand off and merge",
			"",
			"```text",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
		}, "\n")
	}
}

func renderManagedProjectWorkflowGuide(lang string, projectCfg projectConfig, profile initProfile) string {
	projectName := projectCfg.Name
	if projectName == "" {
		projectName = "this repository"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s`는 NambaAI 기준으로 관리됩니다.", projectName),
			"",
			"## 저장소에서 보는 핵심 위치",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.agents/skills/`: Codex가 직접 읽는 skills",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## 작업 순서",
			"",
			"1. `namba project`",
			"2. `namba plan` 또는 `namba fix`",
			"3. `namba run SPEC-XXX`",
			"4. `namba sync`",
			"",
			"## 협업 규칙",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` は NambaAI の規則で管理されています。", projectName),
			"",
			"## 主要な場所",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.agents/skills/`: Codex が直接読む skills",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## 作業順序",
			"",
			"1. `namba project`",
			"2. `namba plan` または `namba fix`",
			"3. `namba run SPEC-XXX`",
			"4. `namba sync`",
			"",
			"## 協業ルール",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` 按照 NambaAI 规则进行管理。", projectName),
			"",
			"## 关键位置",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.agents/skills/`: Codex 直接读取的 skills",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## 工作顺序",
			"",
			"1. `namba project`",
			"2. `namba plan` 或 `namba fix`",
			"3. `namba run SPEC-XXX`",
			"4. `namba sync`",
			"",
			"## 协作规则",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` is managed with NambaAI conventions.", projectName),
			"",
			"## Key locations",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.namba/specs/<SPEC>/reviews/`: advisory product, engineering, design, and readiness artifacts for the current SPEC",
			"- `.agents/skills/`: skills used directly by Codex",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## Work order",
			"",
			"1. `namba project`",
			"2. `namba plan` or `namba fix`",
			"3. Run the relevant plan-review skills and refresh `.namba/specs/<SPEC>/reviews/readiness.md` when the SPEC needs product, engineering, or design critique",
			"4. `namba run SPEC-XXX`",
			"5. `namba sync`",
			"6. `namba pr \"review title\"`",
			"7. `namba land`",
			"",
			"## Run modes",
			"",
			"- `namba run SPEC-XXX`: standard standalone Codex flow in one workspace.",
			"- `namba run SPEC-XXX --solo`: standalone single-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --team`: standalone multi-subagent workflow inside one workspace.",
			"- `namba run SPEC-XXX --parallel`: Namba-managed git worktree fan-out/fan-in, not Codex subagent orchestration.",
			"",
			"## Role routing",
			"",
			"- Default `namba run` stays inside the standalone runner unless specialist signals are strong enough to justify delegation.",
			"- `--solo` uses at most one specialist when one domain clearly dominates the request.",
			"- `--team` prefers one specialist when one domain dominates and expands to two or three only when acceptance spans multiple domains.",
			"- Route UI, responsive, mobile, and design work to `namba-frontend-implementer`, `namba-mobile-engineer`, or `namba-designer`; API, schema, and pipeline work to `namba-backend-implementer` or `namba-data-engineer`; auth, secrets, and compliance work to `namba-security-engineer`; deployment and runtime work to `namba-devops-engineer`.",
			"- Keep the standalone runner as integrator and validation owner, and use `namba-reviewer` last when multiple specialists contribute.",
			"",
			"## Review readiness",
			"",
			"- `namba plan` and `namba fix` seed `.namba/specs/<SPEC>/reviews/product.md`, `engineering.md`, `design.md`, and `readiness.md`.",
			"- `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` keep those artifacts current before execution or GitHub handoff.",
			"- Review readiness is advisory by default: missing review passes are surfaced clearly by `namba run`, `namba sync`, and `namba pr`, but they do not silently become a hard gate.",
			"",
			"## Collaboration rules",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"- `namba sync` stays local; `namba pr` and `namba land` handle GitHub handoff plus merge.",
			"",
		}, "\n")
	}
}
