package namba

import (
	"fmt"
	"strings"
)

const (
	readmeProfileManagedProject = "managed-project"
	readmeProfileNambaCLI       = "namba-cli"
	nambaRepositoryURL          = "https://github.com/Nam-Cheol/namba-ai"
	nambaInstallPowerShell      = "irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex"
	nambaInstallShell           = "curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh"
	nambaWindowsInstallDir      = "%LOCALAPPDATA%\\Programs\\NambaAI\\bin"
	nambaWindowsBinaryPath      = "%LOCALAPPDATA%\\Programs\\NambaAI\\bin\\namba.exe"
	nambaUnixBinaryPath         = "~/.local/bin/namba"
)

func defaultDocsConfig(projectType string) docsConfig {
	manage := strings.TrimSpace(projectType) == "new"
	return docsConfig{
		ManageReadme:        manage,
		ReadmeProfile:       readmeProfileManagedProject,
		DefaultLanguage:     "en",
		AdditionalLanguages: []string{"ko", "ja", "zh"},
	}
}

func normalizeDocsConfig(cfg docsConfig, projectType string) docsConfig {
	defaults := defaultDocsConfig(projectType)
	if strings.TrimSpace(cfg.ReadmeProfile) == "" {
		cfg.ReadmeProfile = defaults.ReadmeProfile
	}
	switch cfg.ReadmeProfile {
	case readmeProfileManagedProject, readmeProfileNambaCLI:
	default:
		cfg.ReadmeProfile = defaults.ReadmeProfile
	}
	cfg.DefaultLanguage = normalizeReadmeLanguage(firstNonBlank(cfg.DefaultLanguage, defaults.DefaultLanguage))
	if !cfg.AdditionalLanguagesSet && len(cfg.AdditionalLanguages) == 0 {
		cfg.AdditionalLanguages = defaults.AdditionalLanguages
	}
	cfg.AdditionalLanguages = uniqueReadmeLanguages(cfg.AdditionalLanguages)
	return cfg
}

func parseCommaSeparatedList(raw string) []string {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	parts := strings.Split(raw, ",")
	var values []string
	for _, part := range parts {
		if value := strings.TrimSpace(part); value != "" {
			values = append(values, value)
		}
	}
	return values
}

func buildReadmeOutputs(projectCfg projectConfig, profile initProfile, cfg docsConfig) map[string]string {
	cfg = normalizeDocsConfig(cfg, projectCfg.ProjectType)
	if !cfg.ManageReadme {
		return nil
	}

	outputs := make(map[string]string)
	for _, lang := range readmeLanguages(cfg) {
		outputs[readmePath(lang)] = renderReadmeRoot(lang, projectCfg, profile, cfg)
		outputs[guidePath("getting-started", lang)] = renderReadmeGuide(lang, "getting-started", projectCfg, profile, cfg)
		outputs[guidePath("workflow-guide", lang)] = renderReadmeGuide(lang, "workflow-guide", projectCfg, profile, cfg)
	}
	return outputs
}

func readmeLanguages(cfg docsConfig) []string {
	languages := []string{normalizeReadmeLanguage(cfg.DefaultLanguage)}
	languages = append(languages, cfg.AdditionalLanguages...)
	return uniqueReadmeLanguages(languages)
}

func uniqueReadmeLanguages(values []string) []string {
	seen := make(map[string]bool)
	var result []string
	for _, value := range values {
		lang := normalizeReadmeLanguage(value)
		if seen[lang] {
			continue
		}
		seen[lang] = true
		result = append(result, lang)
	}
	return result
}

func normalizeReadmeLanguage(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "ko", "kr":
		return "ko"
	case "ja", "jp":
		return "ja"
	case "zh", "cn", "zh-cn", "zh-hans", "zh-hant", "tw":
		return "zh"
	default:
		return "en"
	}
}

func readmePath(lang string) string {
	if normalizeReadmeLanguage(lang) == "en" {
		return "README.md"
	}
	return fmt.Sprintf("README.%s.md", normalizeReadmeLanguage(lang))
}

func guidePath(base, lang string) string {
	lang = normalizeReadmeLanguage(lang)
	if lang == "en" {
		return fmt.Sprintf("docs/%s.md", base)
	}
	return fmt.Sprintf("docs/%s.%s.md", base, lang)
}

func isReadmeManagedPath(rel string) bool {
	switch {
	case rel == readmePath("en"):
		return true
	case strings.HasPrefix(rel, "README.") && strings.HasSuffix(rel, ".md"):
		return true
	case isGeneratedGuidePath(rel, "getting-started"):
		return true
	case isGeneratedGuidePath(rel, "workflow-guide"):
		return true
	default:
		return false
	}
}

func isGeneratedGuidePath(rel, base string) bool {
	defaultPath := guidePath(base, "en")
	if rel == defaultPath {
		return true
	}
	return strings.HasPrefix(rel, "docs/"+base+".") && strings.HasSuffix(rel, ".md")
}

func renderReadmeRoot(lang string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	switch cfg.ReadmeProfile {
	case readmeProfileNambaCLI:
		return renderNambaCLIRoot(lang, cfg)
	default:
		return renderManagedProjectRoot(lang, projectCfg, profile, cfg)
	}
}

func renderReadmeGuide(lang, guide string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	switch cfg.ReadmeProfile {
	case readmeProfileNambaCLI:
		return renderNambaCLIGuide(lang, guide)
	default:
		return renderManagedProjectGuide(lang, guide, projectCfg, profile)
	}
}

func renderGeneratedDocHeader() string {
	return "<!-- Generated by `namba sync`. Edit `.namba/config/sections/docs.yaml` or the README renderer instead of editing this file directly. -->\n"
}

func renderHeroBlock(heroPath, alt string) string {
	if strings.TrimSpace(heroPath) == "" {
		return ""
	}
	return strings.Join([]string{
		"<p align=\"center\">",
		fmt.Sprintf("  <img src=\"%s\" alt=\"%s\" width=\"100%%\" />", heroPath, alt),
		"</p>",
		"",
	}, "\n")
}

func renderLanguageLinks(prefix string) string {
	links := []string{
		fmt.Sprintf("[English](%s%s)", prefix, readmePath("en")),
		fmt.Sprintf("[한국어](%s%s)", prefix, readmePath("ko")),
		fmt.Sprintf("[日本語](%s%s)", prefix, readmePath("ja")),
		fmt.Sprintf("[中文](%s%s)", prefix, readmePath("zh")),
	}
	return strings.Join(links, " | ")
}

func renderRootLinkBar() string {
	return fmt.Sprintf("[Latest Release](%s/releases/latest) | [CI](%s/actions/workflows/ci.yml) | [Security](SECURITY.md)", nambaRepositoryURL, nambaRepositoryURL)
}

func guideFilename(base, lang string) string {
	lang = normalizeReadmeLanguage(lang)
	if lang == "en" {
		return fmt.Sprintf("%s.md", base)
	}
	return fmt.Sprintf("%s.%s.md", base, lang)
}

func localizeGuideLabel(lang, guide string) string {
	lang = normalizeReadmeLanguage(lang)
	switch guide {
	case "workflow-guide":
		switch lang {
		case "ko":
			return "워크플로 가이드"
		case "ja":
			return "ワークフローガイド"
		case "zh":
			return "工作流指南"
		default:
			return "Workflow Guide"
		}
	default:
		switch lang {
		case "ko":
			return "시작 가이드"
		case "ja":
			return "スタートガイド"
		case "zh":
			return "快速开始"
		default:
			return "Getting Started"
		}
	}
}

func renderDocLinkBar(lang string) string {
	return strings.Join([]string{
		fmt.Sprintf("[%s](./%s)", localizeGuideLabel(lang, "getting-started"), guideFilename("getting-started", lang)),
		fmt.Sprintf("[%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
		"[Codex Upstream Reference](./codex-upstream-reference.md)",
	}, " | ")
}

func renderNambaCLIRootLifecycleSection(lang string) []string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return []string{
			"## 설치, 업데이트, 제거",
			"",
			fmt.Sprintf("- 설치 (Windows): `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- 설치 (macOS / Linux): `%s`", nambaInstallShell),
			"- 최신 릴리스로 업데이트: `namba update`",
			"- 특정 릴리스로 고정: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- 제거 (Windows): `%s`를 삭제하고 더 이상 필요 없으면 `%s`를 사용자 `PATH`에서 제거합니다.", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- 제거 (macOS / Linux): `%s`를 삭제하고 더 이상 필요 없으면 설치기가 추가한 `PATH` 줄을 `~/.profile` 또는 `~/.zshrc`에서 제거합니다.", nambaUnixBinaryPath),
			"",
		}
	case "ja":
		return []string{
			"## インストール、アップデート、アンインストール",
			"",
			fmt.Sprintf("- Windows でインストール: `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- macOS / Linux でインストール: `%s`", nambaInstallShell),
			"- 最新リリースへ更新: `namba update`",
			"- 特定バージョンを固定: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- Windows でアンインストール: `%s` を削除し、不要なら `%s` をユーザー `PATH` から外します。", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- macOS / Linux でアンインストール: `%s` を削除し、不要ならインストーラーが追加した `PATH` の行を `~/.profile` または `~/.zshrc` から削除します。", nambaUnixBinaryPath),
			"",
		}
	case "zh":
		return []string{
			"## 安装、更新与卸载",
			"",
			fmt.Sprintf("- 在 Windows 上安装: `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- 在 macOS / Linux 上安装: `%s`", nambaInstallShell),
			"- 更新到最新版本: `namba update`",
			"- 固定到指定版本: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- 在 Windows 上卸载: 删除 `%s`，如果不再需要，再从用户 `PATH` 中移除 `%s`。", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- 在 macOS / Linux 上卸载: 删除 `%s`，如果不再需要，再从 `~/.profile` 或 `~/.zshrc` 中移除安装器添加的 `PATH` 配置。", nambaUnixBinaryPath),
			"",
		}
	default:
		return []string{
			"## Install, Update, and Uninstall",
			"",
			fmt.Sprintf("- Install on Windows: `%s`", nambaInstallPowerShell),
			fmt.Sprintf("- Install on macOS / Linux: `%s`", nambaInstallShell),
			"- Update to the latest release: `namba update`",
			"- Pin a specific release: `namba update --version vX.Y.Z`",
			fmt.Sprintf("- Uninstall on Windows: remove `%s`, then remove `%s` from your user `PATH` if you no longer need it.", nambaWindowsBinaryPath, nambaWindowsInstallDir),
			fmt.Sprintf("- Uninstall on macOS / Linux: remove `%s`, then delete the `PATH` line that the installer added to `~/.profile` or `~/.zshrc` if you no longer need it.", nambaUnixBinaryPath),
			"",
		}
	}
}

func renderNambaCLIUpdateGuideSection(lang string) []string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return []string{
			"## 2. 업데이트",
			"",
			"- 최신 릴리스: `namba update`",
			"- 특정 릴리스: `namba update --version vX.Y.Z`",
			"- 업데이트한 바이너리가 바로 잡히지 않으면 터미널을 다시 여세요.",
			"",
		}
	case "ja":
		return []string{
			"## 2. アップデート",
			"",
			"- 最新リリース: `namba update`",
			"- 特定リリース: `namba update --version vX.Y.Z`",
			"- 更新後のバイナリがすぐ反映されないときは、ターミナルを再起動してください。",
			"",
		}
	case "zh":
		return []string{
			"## 2. 更新",
			"",
			"- 最新版本: `namba update`",
			"- 指定版本: `namba update --version vX.Y.Z`",
			"- 如果更新后的二进制没有立即生效，请重新打开终端。",
			"",
		}
	default:
		return []string{
			"## 2. Update",
			"",
			"- Latest release: `namba update`",
			"- Specific release: `namba update --version vX.Y.Z`",
			"- Re-open the terminal if the updated binary is not picked up immediately.",
			"",
		}
	}
}

func renderNambaCLIUninstallGuideSection(lang string) []string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return []string{
			"## 3. 제거",
			"",
			fmt.Sprintf("- Windows 기본 경로: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux 기본 경로: `%s`", nambaUnixBinaryPath),
			"- `NAMBA_INSTALL_DIR`로 다른 위치에 설치했다면 그 경로의 바이너리를 삭제하세요.",
			"- 더 이상 필요 없으면 해당 경로를 `PATH`에서 제거하세요.",
			"",
		}
	case "ja":
		return []string{
			"## 3. アンインストール",
			"",
			fmt.Sprintf("- Windows の既定パス: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux の既定パス: `%s`", nambaUnixBinaryPath),
			"- `NAMBA_INSTALL_DIR` で別の場所にインストールした場合は、その場所のバイナリを削除してください。",
			"- 不要になったら、対応する `PATH` の項目も削除してください。",
			"",
		}
	case "zh":
		return []string{
			"## 3. 卸载",
			"",
			fmt.Sprintf("- Windows 默认路径: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux 默认路径: `%s`", nambaUnixBinaryPath),
			"- 如果通过 `NAMBA_INSTALL_DIR` 安装到了其他位置，请删除该位置上的二进制文件。",
			"- 如果不再需要，请同时移除对应的 `PATH` 项。",
			"",
		}
	default:
		return []string{
			"## 3. Uninstall",
			"",
			fmt.Sprintf("- Windows default path: `%s`", nambaWindowsBinaryPath),
			fmt.Sprintf("- macOS / Linux default path: `%s`", nambaUnixBinaryPath),
			"- If you installed with `NAMBA_INSTALL_DIR`, remove the binary from that custom location instead.",
			"- Remove the matching `PATH` entry when you no longer need it.",
			"",
		}
	}
}

func renderNambaCLIRoot(lang string, cfg docsConfig) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI는 저장소를 부트스트랩하고, 작업을 SPEC 패키지로 계획하고, 구현 이후 산출물을 동기화하는 Codex-native 워크플로입니다.",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## NambaAI로 할 수 있는 일",
			"",
			"- 빈 디렉터리에서 `namba init .`로 Codex-ready 저장소를 바로 시작할 수 있습니다.",
			"- `namba plan`으로 기능 SPEC를 계획하고, `namba fix --command plan`으로 review 가능한 버그 수정 SPEC를 만들거나, `namba fix`로 현재 workspace에서 직접 수리를 시작할 수 있습니다.",
			"- `namba run SPEC-XXX`로 기본 흐름을 실행하고, `--solo`는 하나의 workspace에서 단일 runner, `--team`은 같은 workspace의 멀티에이전트 실행, `--parallel`은 worktree fan-out/fan-in 실행에 사용한 뒤 `namba sync`, `namba pr`, `namba land`로 마무리합니다.",
			"- 구현 전에 제품, 엔지니어링, 디자인 검토가 필요하면 `$namba-plan-pm-review`, `$namba-plan-eng-review`, `$namba-plan-design-review`를 사용합니다.",
			"- `namba update`와 릴리스 자산으로 팀 전체 CLI 버전을 맞출 수 있습니다.",
			"",
			"## 빠른 시작",
			"",
			"### 1. NambaAI 설치",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 새 저장소 초기화",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Codex에서 작업 시작",
			"",
			"```text",
			"namba project",
			"namba plan \"add login audit logs\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add login audit logs\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Codex에서 쓰는 Command Skill",
			"",
			"- `$namba`: Codex가 적절한 Namba 진입점을 고르게 맡기고 싶을 때 쓰는 일반 라우터입니다.",
			"- `$namba-project`: 시작 전이나 큰 변경 뒤에 프로젝트 문서와 codemap을 새로 고칩니다.",
			"- `$namba-plan`: 다음 기능 SPEC 패키지를 만듭니다.",
			"- `$namba-fix`: `namba fix \"issue description\"`로 현재 workspace에서 직접 버그를 수리하거나, `namba fix --command plan \"issue description\"`으로 review 가능한 버그 수정 SPEC를 만듭니다.",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: SPEC의 product, engineering, design review 산출물과 advisory readiness를 갱신합니다.",
			"- `$namba-run`: 현재 Codex 세션에서 SPEC 패키지를 Namba workflow로 실행합니다.",
			"- `$namba-sync`: README 묶음, 프로젝트 문서, codemap, PR 준비 산출물을 갱신합니다.",
			"- `$namba-pr` / `$namba-land`: 현재 브랜치를 GitHub 리뷰로 넘기고, 체크 통과 후 안전하게 머지합니다.",
			"- `$namba-regen` / `$namba-update`: repo-local Codex 자산을 다시 만들거나 설치된 `namba` CLI를 self-update 합니다.",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"issue description\"` 또는 `namba fix --command plan \"issue description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Codex용 Custom Agents",
			"",
			"- Strategy: `namba-product-manager`가 범위와 acceptance를 다듬고, `namba-planner`가 SPEC를 실행 계획으로 바꿉니다.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, `namba-designer`가 웹 UI, 모바일 실행, 시각 방향을 담당합니다.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, `namba-data-engineer`가 API, 영속성, 마이그레이션, 파이프라인을 담당합니다.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, `namba-reviewer`가 보안 강화, 회귀 신뢰도, CI/CD, 최종 acceptance를 담당합니다.",
			"- General delivery: `namba-implementer`는 여러 도메인을 가로지르지만 더 큰 specialist roster까지는 필요 없는 작업에서 일반 실행 에이전트로 남아 있습니다.",
			"",
			"## 더 읽기",
			"",
			fmt.Sprintf("- [%s](%s): 설치, 업데이트, 제거, init, 첫 실행 흐름", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync / pr / land 차이, run 모드, 생성 산출물, 협업 기본값", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): 이 저장소가 따르는 upstream 기준",
			"- [SECURITY.md](SECURITY.md): 보안 정책",
			"",
			"## 기술 스냅샷",
			"",
			"- `.namba/`는 설정, SPEC 패키지, 프로젝트 문서의 source of truth 입니다.",
			"- `.agents/skills/`는 Codex가 직접 사용하는 repo-local skill surface 입니다.",
			"- `.codex/agents/*.toml`은 product, planning, design, frontend, mobile, backend, data, security, testing, ops, implementation, review 전반의 task-oriented custom agent를 정의합니다.",
			"- `namba update`, `namba regen`, `namba sync`, `namba pr`, `namba land`는 서로 다른 문제를 푸는 명령이므로 섞어서 이해하면 안 됩니다.",
			"",
		)
		return strings.Join(lines, "\n")
	case "ja":
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI は、リポジトリのブートストラップ、作業の SPEC パッケージ化、実装後の成果物同期をまとめる Codex-native ワークフローです。",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## NambaAI でできること",
			"",
			"- 空のディレクトリから `namba init .` で Codex-ready なリポジトリをすぐ始められます。",
			"- `namba plan` で機能 SPEC を計画し、`namba fix --command plan` でレビュー可能なバグ修正 SPEC を作成するか、`namba fix` で現在の workspace から直接修復を始められます。",
			"- `namba run SPEC-XXX` で標準フローを実行し、`--solo` は 1 workspace の単一 runner、`--team` は同じ workspace のマルチエージェント実行、`--parallel` は worktree fan-out/fan-in 実行として使い、その後 `namba sync`、`namba pr`、`namba land` で引き渡します。",
			"- 実装前に product / engineering / design のレビューが必要な場合は `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` を使います。",
			"- `namba update` とリリース資産でチーム全体の CLI バージョンをそろえられます。",
			"",
			"## クイックスタート",
			"",
			"### 1. NambaAI をインストール",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 新しいリポジトリを初期化",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Codex から作業を開始",
			"",
			"```text",
			"namba project",
			"namba plan \"add login audit logs\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add login audit logs\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Codex で使う Command Skill",
			"",
			"- `$namba`: Codex に適切な Namba の入口選択を任せたいときの汎用ルーターです。",
			"- `$namba-project`: 開始前や大きな変更後にプロジェクト文書と codemap を更新します。",
			"- `$namba-plan`: 次の機能 SPEC パッケージを作成します。",
			"- `$namba-fix`: `namba fix \"issue description\"` で現在の workspace から直接修復するか、`namba fix --command plan \"issue description\"` でレビュー可能なバグ修正 SPEC を作成します。",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: SPEC の product / engineering / design review 成果物と advisory readiness を更新します。",
			"- `$namba-run`: 現在の Codex セッションで SPEC パッケージを Namba workflow として実行します。",
			"- `$namba-sync`: README 一式、プロジェクト文書、codemap、PR 用成果物を更新します。",
			"- `$namba-pr` / `$namba-land`: 現在のブランチを GitHub レビューに渡し、チェック通過後に安全にマージします。",
			"- `$namba-regen` / `$namba-update`: repo-local Codex 資産を再生成するか、インストール済み `namba` CLI を self-update します。",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"issue description\"` または `namba fix --command plan \"issue description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Codex 用 Custom Agents",
			"",
			"- Strategy: `namba-product-manager` がスコープと acceptance を整え、`namba-planner` が SPEC を実行計画へ変換します。",
			"- UI and experience: `namba-frontend-architect`、`namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer` が web UI、mobile execution、visual direction を担当します。",
			"- Backend and data: `namba-backend-architect`、`namba-backend-implementer`、`namba-data-engineer` が API、persistence、migration、pipeline を担当します。",
			"- Security and delivery: `namba-security-engineer`、`namba-test-engineer`、`namba-devops-engineer`、`namba-reviewer` が hardening、regression confidence、CI/CD、final acceptance を担当します。",
			"- General delivery: `namba-implementer` は、より大きな specialist roster を組むほどではない複数ドメインの作業で generalist execution agent として残ります。",
			"",
			"## さらに詳しく",
			"",
			fmt.Sprintf("- [%s](%s): インストール、更新、アンインストール、init、初回フロー", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync / pr / land の違い、run mode、生成物、協業ルール", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): このリポジトリが従う upstream 基準",
			"- [SECURITY.md](SECURITY.md): セキュリティポリシー",
			"",
			"## 技術スナップショット",
			"",
			"- `.namba/` は設定、SPEC パッケージ、プロジェクト文書の source of truth です。",
			"- `.agents/skills/` は Codex が直接使う repo-local skill surface です。",
			"- `.codex/agents/*.toml` は product、planning、design、frontend、mobile、backend、data、security、testing、ops、implementation、review をまたぐ task-oriented custom agent を定義します。",
			"- `namba update`、`namba regen`、`namba sync`、`namba pr`、`namba land` は別々の問題を解くコマンドであり、混同すべきではありません。",
			"",
		)
		return strings.Join(lines, "\n")
	case "zh":
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI 是一套 Codex-native 工作流，用来完成仓库初始化、将工作整理成 SPEC 包，以及在实现之后同步项目产物。",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## 你可以用 NambaAI 做什么",
			"",
			"- 在空目录中通过 `namba init .` 直接启动一个 Codex-ready 仓库。",
			"- 用 `namba plan` 规划功能 SPEC，用 `namba fix --command plan` 创建可评审的缺陷修复 SPEC，或者直接用 `namba fix` 在当前 workspace 里修复问题。",
			"- 用 `namba run SPEC-XXX` 运行默认流程，`--solo` 表示单一 workspace 中的单 runner，`--team` 表示同一 workspace 内的多智能体执行，`--parallel` 表示 worktree fan-out/fan-in 执行，然后再用 `namba sync`、`namba pr`、`namba land` 完成交付。",
			"- 如果实现前需要产品、工程或设计评审，可以使用 `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review`。",
			"- 通过 `namba update` 和 release 资产让团队的 CLI 版本保持一致。",
			"",
			"## 快速开始",
			"",
			"### 1. 安装 NambaAI",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. 初始化新仓库",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. 从 Codex 开始工作",
			"",
			"```text",
			"namba project",
			"namba plan \"add login audit logs\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add login audit logs\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Codex 中的 Command Skill",
			"",
			"- `$namba`: 当你希望 Codex 自动选择合适的 Namba 入口时使用的通用路由器。",
			"- `$namba-project`: 在开始前或较大改动后刷新项目文档和 codemap。",
			"- `$namba-plan`: 创建下一个功能 SPEC 包。",
			"- `$namba-fix`: 用 `namba fix \"issue description\"` 在当前 workspace 直接修复问题，或用 `namba fix --command plan \"issue description\"` 创建可评审的缺陷修复 SPEC。",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: 更新 SPEC 的 product / engineering / design review 产物以及 advisory readiness 摘要。",
			"- `$namba-run`: 在当前 Codex 会话中用 Namba workflow 执行 SPEC 包。",
			"- `$namba-sync`: 刷新 README 套件、项目文档、codemap 和 PR 交接产物。",
			"- `$namba-pr` / `$namba-land`: 将当前分支提交到 GitHub 评审，并在检查通过后安全合并。",
			"- `$namba-regen` / `$namba-update`: 重新生成 repo-local Codex 资产，或自更新已安装的 `namba` CLI。",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"issue description\"` 或 `namba fix --command plan \"issue description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Codex 自定义 Agents",
			"",
			"- Strategy: `namba-product-manager` 负责收敛范围和 acceptance，`namba-planner` 把 SPEC 转成执行计划。",
			"- UI and experience: `namba-frontend-architect`、`namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer` 负责 web UI、mobile execution 和 visual direction。",
			"- Backend and data: `namba-backend-architect`、`namba-backend-implementer`、`namba-data-engineer` 负责 API、persistence、migration 和 pipeline。",
			"- Security and delivery: `namba-security-engineer`、`namba-test-engineer`、`namba-devops-engineer`、`namba-reviewer` 负责 hardening、regression confidence、CI/CD 和 final acceptance。",
			"- General delivery: `namba-implementer` 在任务跨多个领域但还不需要更大 specialist roster 时，继续作为通用执行 agent。",
			"",
			"## 继续阅读",
			"",
			fmt.Sprintf("- [%s](%s): 安装、更新、卸载、init 和首次运行流程", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update / regen / sync / pr / land 的区别、run 模式、生成产物和协作默认值", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): 本仓库遵循的 upstream 基线",
			"- [SECURITY.md](SECURITY.md): 安全策略",
			"",
			"## 技术概览",
			"",
			"- `.namba/` 是配置、SPEC 包和项目文档的 source of truth。",
			"- `.agents/skills/` 是 Codex 直接使用的 repo-local skill surface。",
			"- `.codex/agents/*.toml` 定义了覆盖 product、planning、design、frontend、mobile、backend、data、security、testing、ops、implementation、review 的 task-oriented custom agent。",
			"- `namba update`、`namba regen`、`namba sync`、`namba pr`、`namba land` 各自解决不同的问题，不应混用理解。",
			"",
		)
		return strings.Join(lines, "\n")
	default:
		lines := []string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, "NambaAI"),
			"# NambaAI",
			"",
			"NambaAI is a Codex-native workflow for bootstrapping repositories, planning work as SPEC packages, and syncing project artifacts after implementation.",
			"",
			renderLanguageLinks(""),
			"",
			renderRootLinkBar(),
			"",
			"## What You Can Do With NambaAI",
			"",
			"- Bootstrap a Codex-ready repository from an empty directory with `namba init .`.",
			"- Plan feature SPEC work with `namba plan`, create a reviewable bugfix SPEC with `namba fix --command plan`, or start direct repair in the current workspace with `namba fix`.",
			"- Execute work with `namba run SPEC-XXX` for the default flow, use `--solo` for a single runner in one workspace, `--team` for same-workspace multi-agent execution, or `--parallel` for worktree fan-out/fan-in before handing off with `namba sync`, `namba pr`, and `namba land`.",
			"- Run explicit plan reviews with `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` when a SPEC needs product, engineering, or design critique before implementation.",
			"- Keep CLI versions aligned across the team with `namba update` and release assets.",
			"",
			"## Quick Start",
			"",
			"### 1. Install NambaAI",
			"",
			"```powershell",
			"irm https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.ps1 | iex",
			"```",
			"",
			"```bash",
			"curl -fsSL https://raw.githubusercontent.com/Nam-Cheol/namba-ai/main/install.sh | sh",
			"```",
			"",
			"### 2. Bootstrap a new repository",
			"",
			"```text",
			"namba init .",
			"```",
			"",
			"### 3. Start working from Codex",
			"",
			"```text",
			"namba project",
			"namba plan \"add login audit logs\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add login audit logs\"",
			"namba land",
			"```",
			"",
		}
		lines = append(lines, renderNambaCLIRootLifecycleSection(lang)...)
		lines = append(lines,
			"## Command Skills In Codex",
			"",
			"- `$namba`: general router when you want Codex to choose the right Namba workflow entry point.",
			"- `$namba-project`: refresh project docs and codemaps before starting or after larger changes.",
			"- `$namba-plan`: create the next feature SPEC package.",
			"- `$namba-fix`: run direct repair in the current workspace with `namba fix \"issue description\"` or create a reviewable bugfix SPEC with `namba fix --command plan \"issue description\"`.",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: update product, engineering, or design review artifacts plus the advisory readiness summary for a SPEC.",
			"- `$namba-run`: execute a SPEC package through the Namba workflow in the current Codex session.",
			"- `$namba-sync`: refresh README bundles, project docs, codemaps, and PR-ready artifacts.",
			"- `$namba-pr` / `$namba-land`: hand off the current branch for GitHub review, then merge it safely after checks pass.",
			"- `$namba-regen` / `$namba-update`: regenerate repo-local Codex assets or self-update the installed `namba` CLI.",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"issue description\"` or `namba fix --command plan \"issue description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Custom Agents In Codex",
			"",
			"- Strategy: `namba-product-manager` shapes scope and acceptance, and `namba-planner` turns a SPEC into an execution plan.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, and `namba-designer` cover web UI, mobile execution, and visual direction.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, and `namba-data-engineer` cover APIs, persistence, migrations, and pipelines.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, and `namba-reviewer` cover hardening, regression confidence, CI/CD, and final acceptance.",
			"- General delivery: `namba-implementer` remains the generalist execution agent when a task spans multiple domains but does not justify a larger specialist team.",
			"",
			"## Need More Detail?",
			"",
			fmt.Sprintf("- [%s](%s): installation, updates, uninstall, init, and first-run flow", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s): update vs regen vs sync vs pr vs land, run modes, generated assets, and collaboration defaults", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md): upstream baseline this repository follows",
			"- [SECURITY.md](SECURITY.md): security policy",
			"",
			"## Technical Snapshot",
			"",
			"- `.namba/` is the source of truth for config, SPEC packages, and project docs.",
			"- `.agents/skills/` is the repo-local skill surface used by Codex.",
			"- `.codex/agents/*.toml` defines task-oriented custom agents across product, planning, design, frontend, mobile, backend, data, security, testing, ops, implementation, and review.",
			"- `namba update`, `namba regen`, `namba sync`, `namba pr`, and `namba land` solve different problems and should not be mixed.",
			"",
		)
		return strings.Join(lines, "\n")
	}
}

func renderManagedProjectRoot(lang string, projectCfg projectConfig, profile initProfile, cfg docsConfig) string {
	title := projectCfg.Name
	if title == "" {
		title = "Project"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"이 저장소는 NambaAI로 관리됩니다. 이 README는 `namba sync`가 생성하며, 기여자가 코드를 건드리기 전에 작업 흐름을 빠르게 이해할 수 있도록 돕습니다.",
			"",
			renderLanguageLinks(""),
			"",
			"## 이 저장소에서 할 수 있는 일",
			"",
			"- `namba project`로 현재 구조와 핵심 문서를 새로 고칩니다.",
			"- `namba plan`으로 기능 SPEC를 만들고, `namba fix --command plan`으로 버그 수정 SPEC를 만들거나, `namba fix`로 현재 workspace에서 직접 수리 경로를 시작합니다.",
			"- SPEC에 명시적 사전 검토가 필요하면 `$namba-plan-pm-review`, `$namba-plan-eng-review`, `$namba-plan-design-review`를 사용합니다.",
			"- `namba run SPEC-XXX`로 기본 흐름을 실행하고, `--solo`는 하나의 workspace에서 단일 runner, `--team`은 같은 workspace의 멀티에이전트 실행, `--parallel`은 worktree fan-out/fan-in 실행에 사용합니다.",
			"- 브랜치, PR, Codex review 흐름을 기여자 간에 일관되게 유지합니다.",
			"",
			"## 빠르게 시작하기",
			"",
			"```text",
			"namba project",
			"namba plan \"work description\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
			"## 더 읽기",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 현재 기본값",
			"",
			fmt.Sprintf("- 작업 언어: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR 대상 브랜치: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex 리뷰 코멘트: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"このリポジトリは NambaAI で管理されています。この README は `namba sync` によって生成され、コントリビューターがコードに触る前に作業フローを素早く理解できるようにします。",
			"",
			renderLanguageLinks(""),
			"",
			"## このリポジトリでできること",
			"",
			"- `namba project` で現在の構造と主要ドキュメントを更新します。",
			"- `namba plan` で機能 SPEC を作成し、`namba fix --command plan` でバグ修正 SPEC を作成するか、`namba fix` で現在の workspace から直接修復を始めます。",
			"- SPEC に明示的な事前レビューが必要なら `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` を使います。",
			"- `namba run SPEC-XXX` で標準フローを実行し、`--solo` は 1 workspace の単一 runner、`--team` は同じ workspace のマルチエージェント実行、`--parallel` は worktree fan-out/fan-in 実行として使います。",
			"- ブランチ、PR、Codex review フローをコントリビューター間で一貫させます。",
			"",
			"## すぐ始める",
			"",
			"```text",
			"namba project",
			"namba plan \"work description\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
			"## さらに読む",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 現在の既定値",
			"",
			fmt.Sprintf("- 作業言語: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR 対象ブランチ: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex review コメント: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"这个仓库由 NambaAI 管理。README 由 `namba sync` 生成，目的是让贡献者在修改代码前就能快速理解工作流。",
			"",
			renderLanguageLinks(""),
			"",
			"## 这个仓库里可以做什么",
			"",
			"- 运行 `namba project` 刷新当前结构和核心文档。",
			"- 用 `namba plan` 创建功能 SPEC，用 `namba fix --command plan` 创建缺陷修复 SPEC，或者直接用 `namba fix` 在当前 workspace 开始修复。",
			"- 如果某个 SPEC 需要明确的实现前评审，可以使用 `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review`。",
			"- 用 `namba run SPEC-XXX` 运行标准流程，`--solo` 表示单一 workspace 中的单 runner，`--team` 表示同一 workspace 内的多智能体执行，`--parallel` 表示 worktree fan-out/fan-in 执行。",
			"- 让 branch、PR 和 Codex review 流程在不同贡献者之间保持一致。",
			"",
			"## 快速开始",
			"",
			"```text",
			"namba project",
			"namba plan \"work description\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
			"## 继续阅读",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## 当前默认值",
			"",
			fmt.Sprintf("- 工作语言: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR 目标分支: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex review 评论: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			renderHeroBlock(cfg.HeroImage, title),
			fmt.Sprintf("# %s", title),
			"",
			"This repository is managed with NambaAI. The README is generated by `namba sync` so contributors can understand the workflow before they touch the code.",
			"",
			renderLanguageLinks(""),
			"",
			"## What You Can Do In This Repository",
			"",
			"- Run `namba project` to refresh the current structure and core docs.",
			"- Use `namba plan` for feature SPEC work, `namba fix --command plan` for bugfix SPEC work, or `namba fix` for direct repair in the current workspace.",
			"- Use `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` when a SPEC needs explicit pre-implementation review depth.",
			"- Execute `namba run SPEC-XXX` for the default flow, or use `--solo` for a single runner in one workspace, `--team` for same-workspace multi-agent execution, and `--parallel` for worktree fan-out/fan-in execution.",
			"- Keep branch, PR, and Codex review flow consistent across contributors.",
			"",
			"## Start Fast",
			"",
			"```text",
			"namba project",
			"namba plan \"work description\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
			"## Command Skills In Codex",
			"",
			"- `$namba`: general router when you want Codex to choose the right Namba entry point.",
			"- `$namba-project`: refresh docs and codemaps before implementation or after larger changes.",
			"- `$namba-plan`: create the next feature SPEC package.",
			"- `$namba-fix`: run direct repair in the current workspace with `namba fix \"issue description\"` or create a reviewable bugfix SPEC with `namba fix --command plan \"issue description\"`.",
			"- `$namba-plan-pm-review` / `$namba-plan-eng-review` / `$namba-plan-design-review`: update product, engineering, or design review artifacts plus the advisory readiness summary for a SPEC.",
			"- `$namba-run`: execute the current SPEC package with the Namba run workflow.",
			"- `$namba-sync`: refresh README bundles, project docs, codemaps, and PR-ready artifacts.",
			"- `$namba-pr` / `$namba-land`: prepare GitHub review handoff, then merge safely after checks pass.",
			"- `$namba-regen` / `$namba-update`: regenerate repo-local Codex assets or update the installed `namba` CLI.",
			"",
			"## Skill To Command Mapping",
			"",
			"- `$namba-project` -> `namba project`",
			"- `$namba-plan` -> `namba plan \"description\"`",
			"- `$namba-fix` -> `namba fix \"issue description\"` or `namba fix --command plan \"issue description\"`",
			"- `$namba-run` -> `namba run SPEC-XXX`",
			"- `$namba-sync` -> `namba sync`",
			"- `$namba-pr` -> `namba pr \"title\"`",
			"- `$namba-land` -> `namba land`",
			"- `$namba-regen` -> `namba regen`",
			"- `$namba-update` -> `namba update [--version vX.Y.Z]`",
			"",
			"## Custom Agents In Codex",
			"",
			"- Strategy: `namba-product-manager` shapes scope and acceptance, and `namba-planner` turns a SPEC into an execution plan.",
			"- UI and experience: `namba-frontend-architect`, `namba-frontend-implementer`, `namba-mobile-engineer`, and `namba-designer` cover web UI, mobile execution, and visual direction.",
			"- Backend and data: `namba-backend-architect`, `namba-backend-implementer`, and `namba-data-engineer` cover APIs, persistence, migrations, and pipelines.",
			"- Security and delivery: `namba-security-engineer`, `namba-test-engineer`, `namba-devops-engineer`, and `namba-reviewer` cover hardening, regression confidence, CI/CD, and final acceptance.",
			"- General delivery: `namba-implementer` remains available when a task spans multiple domains but does not justify a larger specialist roster.",
			"",
			"## Read More",
			"",
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "getting-started"), guidePath("getting-started", lang)),
			fmt.Sprintf("- [%s](%s)", localizeGuideLabel(lang, "workflow-guide"), guidePath("workflow-guide", lang)),
			"- [Codex Upstream Reference](docs/codex-upstream-reference.md)",
			"",
			"## Current Defaults",
			"",
			fmt.Sprintf("- Working language: %s", humanLanguageName(profile.DocumentationLanguage)),
			fmt.Sprintf("- PR base branch: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- Codex review comment: `%s`", codexReviewComment(profile)),
			"- source of truth: `.namba/`",
			"",
		}, "\n")
	}
}

func renderNambaCLIGuide(lang, guide string) string {
	switch guide {
	case "workflow-guide":
		return renderNambaCLIWorkflowGuide(lang)
	default:
		return renderNambaCLIGettingStarted(lang)
	}
}

func renderManagedProjectGuide(lang, guide string, projectCfg projectConfig, profile initProfile) string {
	switch guide {
	case "workflow-guide":
		return renderManagedProjectWorkflowGuide(lang, projectCfg, profile)
	default:
		return renderManagedProjectGettingStarted(lang, projectCfg)
	}
}

func renderNambaCLIGettingStarted(lang string) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 설치",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- Windows에서 저장소 안쪽 작업을 많이 한다면 Codex CLI 경험을 위해 WSL workspace를 권장합니다.",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- 기본 경로가 아닌 곳에 설치하려면 `NAMBA_INSTALL_DIR`를 사용하세요.",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. 새 저장소 부트스트랩",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard는 작업 언어, approval_policy, sandbox_mode, PR 언어, Codex agent mode를 함께 정렬합니다.",
			"",
			"## 5. 기본 Codex 흐름 실행",
			"",
			"```text",
			"namba project",
			"namba plan \"add dashboard filters\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add dashboard filters\"",
			"namba land",
			"```",
			"",
			"## 6. 다음 문서",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	case "ja":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. インストール",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- Windows でリポジトリ内の作業が多いなら、Codex CLI 体験のために WSL workspace を推奨します。",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- 既定以外の場所へ入れたい場合は `NAMBA_INSTALL_DIR` を使ってください。",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. 新しいリポジトリをブートストラップ",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard は作業言語、approval_policy、sandbox_mode、PR 言語、Codex agent mode をまとめてそろえます。",
			"",
			"## 5. 基本の Codex フローを実行",
			"",
			"```text",
			"namba project",
			"namba plan \"add dashboard filters\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add dashboard filters\"",
			"namba land",
			"```",
			"",
			"## 6. 次に読む文書",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	case "zh":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 安装",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- 如果你经常在 Windows 下直接在仓库里工作，建议使用 WSL workspace 以获得更好的 Codex CLI 体验。",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- 如果需要安装到非默认位置，请使用 `NAMBA_INSTALL_DIR`。",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. 初始化新仓库",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"wizard 会统一工作语言、approval_policy、sandbox_mode、PR 语言以及 Codex agent mode。",
			"",
			"## 5. 运行基础 Codex 流程",
			"",
			"```text",
			"namba project",
			"namba plan \"add dashboard filters\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add dashboard filters\"",
			"namba land",
			"```",
			"",
			"## 6. 接下来阅读",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	default:
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. Install",
			"",
			fmt.Sprintf("- Windows: `%s`", nambaInstallPowerShell),
			"- For the best Codex CLI experience on Windows, use a WSL workspace when you work inside a repository.",
			fmt.Sprintf("- macOS / Linux: `%s`", nambaInstallShell),
			"- Use `NAMBA_INSTALL_DIR` when you want a non-default install location.",
			"",
		}
		lines = append(lines, renderNambaCLIUpdateGuideSection(lang)...)
		lines = append(lines, renderNambaCLIUninstallGuideSection(lang)...)
		lines = append(lines,
			"## 4. Bootstrap a new repository",
			"",
			"```text",
			"mkdir my-project",
			"cd my-project",
			"namba init .",
			"```",
			"",
			"The wizard aligns working language, approval_policy, sandbox_mode, PR language, and Codex agent mode.",
			"",
			"## 5. Run the basic Codex flow",
			"",
			"```text",
			"namba project",
			"namba plan \"add dashboard filters\"",
			"namba run SPEC-001",
			"namba sync",
			"namba pr \"add dashboard filters\"",
			"namba land",
			"```",
			"",
			"## 6. Read next",
			"",
			fmt.Sprintf("- [%s](./%s)", localizeGuideLabel(lang, "workflow-guide"), guideFilename("workflow-guide", lang)),
			"- [Codex Upstream Reference](./codex-upstream-reference.md)",
			"",
		)
		return strings.Join(lines, "\n")
	}
}

func renderNambaCLIWorkflowGuide(lang string) string {
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`, `regen`, `sync`, `pr`, `land`는 서로 다른 명령입니다",
			"",
			"- `namba update`: 설치된 CLI를 GitHub Release 자산 기준으로 self-update 합니다.",
			"- `namba regen`: AGENTS, skills, custom agents, repo Codex config 같은 template-generated asset을 다시 생성합니다.",
			"- `namba sync`: README, 프로젝트 문서, codemap, advisory review readiness, PR checklist, release notes를 갱신합니다.",
			"- `namba pr`: 기본적으로 sync와 validation을 돌리고, 현재 브랜치를 commit/push 한 뒤 PR을 만들거나 재사용하고 Codex review marker를 보장합니다.",
			"- `namba land`: 필요하면 체크를 기다리고, PR이 깨끗할 때만 머지한 뒤 로컬 `main`을 안전하게 갱신합니다.",
			"",
			"## `namba plan`과 `namba fix`",
			"",
			"- `namba plan \"description\"`: 다음 기능 SPEC 패키지와 review artifact를 만듭니다.",
			"- `namba fix --command plan \"issue description\"`: 버그 수정 SPEC 패키지와 review artifact를 만듭니다.",
			"- `namba fix \"issue description\"`: 현재 workspace에서 direct repair를 시작합니다.",
			"- `namba fix --command run \"issue description\"`: 같은 direct-repair 경로를 명시적으로 선택합니다.",
			"- `namba plan --help`와 `namba fix --help`: read-only help/option probing 경로이며 SPEC를 만들지 않습니다.",
			"",
			"## `namba run` 모드",
			"",
			"- `namba run SPEC-XXX`: 하나의 workspace에서 실행하는 표준 standalone Codex 흐름입니다.",
			"- `namba run SPEC-XXX --solo`: 하나의 workspace에서 단일 runner를 사용합니다.",
			"- `namba run SPEC-XXX --team`: 같은 workspace 안에서 멀티에이전트 실행을 조율합니다.",
			"- `namba run SPEC-XXX --parallel`: Codex subagent orchestration이 아니라 Namba가 관리하는 git worktree fan-out/fan-in 입니다.",
			"",
			"## 역할 라우팅",
			"",
			"- 기본 `namba run`은 prompt에 강한 specialist 신호가 없으면 standalone runner에 머뭅니다.",
			"- `--solo`는 위험을 실질적으로 줄일 specialist 한 명이 있을 때만 분기하고, `--team`은 acceptance가 여러 도메인에 걸칠 때 여러 specialist와 마지막 reviewer를 같은 workspace 안에서 조율합니다.",
			"- UI, responsive, mobile, design 작업은 `namba-frontend-implementer`, `namba-mobile-engineer`, `namba-designer`로, API, schema, pipeline 작업은 `namba-backend-implementer`, `namba-data-engineer`로, auth, secrets, compliance는 `namba-security-engineer`로, deployment와 runtime은 `namba-devops-engineer`로 보냅니다.",
			"- standalone runner는 integrator이자 validation owner로 두고, uncontrolled swarm 대신 마지막 acceptance는 `namba-reviewer`에게 맡깁니다.",
			"",
			"## 리뷰 준비도",
			"",
			"- `namba plan`과 `namba fix --command plan`은 `.namba/specs/<SPEC>/reviews/product.md`, `engineering.md`, `design.md`, `readiness.md`를 seed 합니다.",
			"- 구현이나 GitHub handoff 전에 `$namba-plan-pm-review`, `$namba-plan-eng-review`, `$namba-plan-design-review`로 review 산출물을 최신 상태로 유지하세요.",
			"- `namba regen` 또는 `namba sync`가 생성된 instruction surface를 바꾸면, 긴 repair loop를 이어 가기 전에 fresh Codex session을 시작해 갱신된 지침을 다시 불러오세요.",
			"- 리뷰 통과가 없어도 기본적으로 advisory 상태를 유지합니다. `namba run`, `namba sync`, `namba pr`는 readiness 요약을 보여주지만 조용히 hard gate로 바꾸지는 않습니다.",
			"",
			"## 주요 생성 산출물",
			"",
			"- `.namba/`: config, SPEC packages, project docs, logs",
			"- `.namba/specs/<SPEC>/reviews/`: 각 SPEC의 advisory product, engineering, design, readiness artifact",
			"- `.agents/skills/`: Codex가 직접 사용하는 repo-local skills",
			"- `.codex/config.toml`: repo-local Codex defaults 와 Namba-managed MCP preset",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary, release notes, checklist, codemap",
			"",
			"## 협업 기본값",
			"",
			"- 작업은 전용 브랜치에서 진행합니다.",
			"- `namba pr`은 `main`을 대상으로 하고, 설정된 PR 언어와 review marker를 그대로 유지합니다.",
			"- `namba land`는 깨끗한 PR만 머지하고, 관련 없는 로컬 작업을 덮어쓰지 않은 채 `main`을 갱신합니다.",
			"- GitHub review 요청은 `@codex review`를 사용합니다.",
			"",
			"## 릴리스 흐름",
			"",
			"- `namba release`는 `main`에서 clean working tree를 요구합니다.",
			"- `--push`는 새 태그와 `main`을 함께 push한 뒤 GitHub Release workflow를 트리거합니다.",
			"",
		}
		return strings.Join(lines, "\n")
	case "ja":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`, `regen`, `sync`, `pr`, `land` はそれぞれ別のコマンドです",
			"",
			"- `namba update`: インストール済み CLI を GitHub Release 資産から self-update します。",
			"- `namba regen`: AGENTS、skills、custom agents、repo Codex config などの template-generated asset を再生成します。",
			"- `namba sync`: README、project docs、codemap、advisory review readiness、PR checklist、release notes を更新します。",
			"- `namba pr`: 既定で sync と validation を実行し、現在のブランチを commit / push した上で PR を作成または再利用し、Codex review marker を保証します。",
			"- `namba land`: 必要なら checks を待ち、PR が clean なときだけ merge してから local `main` を安全に更新します。",
			"",
			"## `namba plan` と `namba fix`",
			"",
			"- `namba plan \"description\"`: 次の機能 SPEC パッケージと review artifact を作成します。",
			"- `namba fix --command plan \"issue description\"`: バグ修正 SPEC パッケージと review artifact を作成します。",
			"- `namba fix \"issue description\"`: 現在の workspace で direct repair を始めます。",
			"- `namba fix --command run \"issue description\"`: 同じ direct-repair path を明示的に選びます。",
			"- `namba plan --help` と `namba fix --help`: read-only の help / option probing であり、SPEC を作成しません。",
			"",
			"## `namba run` モード",
			"",
			"- `namba run SPEC-XXX`: 1 つの workspace で動く標準 standalone Codex flow です。",
			"- `namba run SPEC-XXX --solo`: 1 つの workspace で単一 runner を使います。",
			"- `namba run SPEC-XXX --team`: 同じ workspace 内で multi-agent execution を調整します。",
			"- `namba run SPEC-XXX --parallel`: Codex subagent orchestration ではなく、Namba 管理の git worktree fan-out/fan-in です。",
			"",
			"## ロールルーティング",
			"",
			"- 既定の `namba run` は、prompt に強い specialist signal がない限り standalone runner に留まります。",
			"- `--solo` は 1 人の specialist で実質的にリスクを下げられる場合だけ分岐し、`--team` は acceptance が複数ドメインにまたがるときに複数 specialist と最終 reviewer を同じ workspace 内で調整します。",
			"- UI、responsive、mobile、design は `namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer` に、API、schema、pipeline は `namba-backend-implementer`、`namba-data-engineer` に、auth、secrets、compliance は `namba-security-engineer` に、deployment と runtime は `namba-devops-engineer` に割り当てます。",
			"- standalone runner は integrator かつ validation owner とし、制御不能な swarm を広げる代わりに最終 acceptance は `namba-reviewer` に任せます。",
			"",
			"## レビュー準備度",
			"",
			"- `namba plan` と `namba fix --command plan` は `.namba/specs/<SPEC>/reviews/product.md`、`engineering.md`、`design.md`、`readiness.md` を seed します。",
			"- 実装または GitHub handoff の前に `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` で review artifact を最新に保ってください。",
			"- `namba regen` または `namba sync` が生成された instruction surface を変えた場合は、長い repair loop を続ける前に fresh Codex session を開始して更新済み guidance を読み直してください。",
			"- review pass が欠けていても既定では advisory のままです。`namba run`、`namba sync`、`namba pr` は readiness summary を表示しますが、黙って hard gate にはしません。",
			"",
			"## 主な生成物",
			"",
			"- `.namba/`: config、SPEC packages、project docs、logs",
			"- `.namba/specs/<SPEC>/reviews/`: 各 SPEC の advisory product / engineering / design / readiness artifact",
			"- `.agents/skills/`: Codex が直接使う repo-local skills",
			"- `.codex/config.toml`: repo-local Codex defaults と Namba-managed MCP preset",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary、release notes、checklist、codemap",
			"",
			"## 協業の既定値",
			"",
			"- 作業は専用ブランチで進めます。",
			"- `namba pr` は `main` を対象にし、設定済みの PR 言語と review marker をそのまま維持します。",
			"- `namba land` は clean な PR だけを merge し、無関係な local work を壊さずに `main` を更新します。",
			"- GitHub review request には `@codex review` を使います。",
			"",
			"## リリースフロー",
			"",
			"- `namba release` は `main` 上の clean working tree を要求します。",
			"- `--push` は新しい tag と `main` をまとめて push し、その後 GitHub Release workflow を起動します。",
			"",
		}
		return strings.Join(lines, "\n")
	case "zh":
		lines := []string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`、`regen`、`sync`、`pr`、`land` 是不同的命令",
			"",
			"- `namba update`: 从 GitHub Release 资产对已安装的 CLI 做 self-update。",
			"- `namba regen`: 重新生成 AGENTS、skills、custom agents、repo Codex config 等 template-generated asset。",
			"- `namba sync`: 刷新 README、project docs、codemap、advisory review readiness、PR checklist 和 release notes。",
			"- `namba pr`: 默认先跑 sync 和 validation，把当前分支 commit / push 后创建或复用 PR，并确保 Codex review marker 存在。",
			"- `namba land`: 需要时等待 checks，只在 PR clean 时 merge，然后安全更新本地 `main`。",
			"",
			"## `namba plan` 和 `namba fix`",
			"",
			"- `namba plan \"description\"`: 创建下一个功能 SPEC 包和 review artifact。",
			"- `namba fix --command plan \"issue description\"`: 创建缺陷修复 SPEC 包和 review artifact。",
			"- `namba fix \"issue description\"`: 在当前 workspace 启动 direct repair。",
			"- `namba fix --command run \"issue description\"`: 显式选择同一个 direct-repair 路径。",
			"- `namba plan --help` 和 `namba fix --help`: 属于 read-only 的 help / option probing，不会创建 SPEC。",
			"",
			"## `namba run` 模式",
			"",
			"- `namba run SPEC-XXX`: 在单一 workspace 中运行的标准 standalone Codex flow。",
			"- `namba run SPEC-XXX --solo`: 在单一 workspace 中使用单 runner。",
			"- `namba run SPEC-XXX --team`: 在同一 workspace 内协调 multi-agent execution。",
			"- `namba run SPEC-XXX --parallel`: 这不是 Codex subagent orchestration，而是由 Namba 管理的 git worktree fan-out/fan-in。",
			"",
			"## 角色路由",
			"",
			"- 默认的 `namba run` 会停留在 standalone runner，除非 prompt 明确显示出强烈的 specialist signal。",
			"- `--solo` 只会在一个 specialist 能显著降低风险时分流，`--team` 则会在 acceptance 跨多个领域时，在同一 workspace 内协调多个 specialist 和最后的 reviewer。",
			"- UI、responsive、mobile、design 交给 `namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer`；API、schema、pipeline 交给 `namba-backend-implementer`、`namba-data-engineer`；auth、secrets、compliance 交给 `namba-security-engineer`；deployment 和 runtime 交给 `namba-devops-engineer`。",
			"- 让 standalone runner 继续担任 integrator 和 validation owner，最终 acceptance 交给 `namba-reviewer`，不要扩散成失控的 swarm。",
			"",
			"## 评审准备度",
			"",
			"- `namba plan` 和 `namba fix --command plan` 会 seed `.namba/specs/<SPEC>/reviews/product.md`、`engineering.md`、`design.md`、`readiness.md`。",
			"- 在实现或 GitHub handoff 之前，使用 `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` 保持 review artifact 最新。",
			"- 如果 `namba regen` 或 `namba sync` 改变了生成的 instruction surface，请在继续长 repair loop 之前启动一个 fresh Codex session，以重新加载更新后的 guidance。",
			"- 即使 review pass 缺失，默认也只是 advisory。`namba run`、`namba sync`、`namba pr` 会展示 readiness summary，但不会悄悄变成 hard gate。",
			"",
			"## 主要生成产物",
			"",
			"- `.namba/`: config、SPEC packages、project docs、logs",
			"- `.namba/specs/<SPEC>/reviews/`: 每个 SPEC 的 advisory product / engineering / design / readiness artifact",
			"- `.agents/skills/`: Codex 直接使用的 repo-local skills",
			"- `.codex/config.toml`: repo-local Codex defaults 和 Namba-managed MCP preset",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary、release notes、checklist、codemap",
			"",
			"## 协作默认值",
			"",
			"- 工作应在专用分支上进行。",
			"- `namba pr` 以 `main` 为目标，并保持配置中的 PR 语言和 review marker 一致。",
			"- `namba land` 只合并 clean PR，并在不覆盖无关本地改动的前提下更新 `main`。",
			"- GitHub review request 使用 `@codex review`。",
			"",
			"## 发布流程",
			"",
			"- `namba release` 要求 `main` 上是 clean working tree。",
			"- `--push` 会同时 push 新 tag 和 `main`，然后触发 GitHub Release workflow。",
			"",
		}
		return strings.Join(lines, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## `update`, `regen`, `sync`, `pr`, and `land` are different commands",
			"",
			"- `namba update`: self-update the installed CLI from GitHub Release assets",
			"- `namba regen`: regenerate AGENTS, skills, custom agents, and repo Codex config",
			"- `namba sync`: refresh README, project docs, codemaps, advisory review readiness, PR checklists, and release notes",
			"- `namba pr`: run sync plus validation by default, commit and push the current branch, open or reuse the PR, and ensure the Codex review marker exists",
			"- `namba land`: optionally wait for checks, merge only when the PR is clean, and update local `main` safely",
			"",
			"## `namba plan` and `namba fix`",
			"",
			"- `namba plan \"description\"`: create the next feature SPEC package and review artifacts.",
			"- `namba fix --command plan \"issue description\"`: create a bugfix SPEC package plus review artifacts.",
			"- `namba fix \"issue description\"`: direct repair in the current workspace.",
			"- `namba fix --command run \"issue description\"`: explicit form of the same direct-repair path.",
			"- `namba plan --help` and `namba fix --help`: read-only help and option discovery; they must not create a SPEC package.",
			"",
			"## `namba run` modes",
			"",
			"- `namba run SPEC-XXX`: standard standalone Codex flow in one workspace.",
			"- `namba run SPEC-XXX --solo`: a single runner in one workspace.",
			"- `namba run SPEC-XXX --team`: same-workspace multi-agent execution.",
			"- `namba run SPEC-XXX --parallel`: Namba-managed git worktree fan-out/fan-in, not Codex subagent orchestration.",
			"",
			"## Role routing",
			"",
			"- Default `namba run` stays in the standalone runner unless the prompt shows a strong specialist signal.",
			"- `--solo` keeps the run inside one runner unless a single specialist would materially reduce risk; `--team` keeps the work in one workspace while coordinating multiple specialists plus a final reviewer when acceptance spans multiple domains.",
			"- Route UI, responsive, mobile, and design work to `namba-frontend-implementer`, `namba-mobile-engineer`, or `namba-designer`; API, schema, and pipeline work to `namba-backend-implementer` or `namba-data-engineer`; auth, secrets, and compliance work to `namba-security-engineer`; deployment and runtime work to `namba-devops-engineer`.",
			"- Keep the standalone runner as integrator and validation owner; use `namba-reviewer` for the final acceptance pass rather than growing an uncontrolled swarm.",
			"",
			"## Review readiness",
			"",
			"- `namba plan` and `namba fix --command plan` seed `.namba/specs/<SPEC>/reviews/product.md`, `engineering.md`, `design.md`, and `readiness.md`.",
			"- Use `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` to keep those artifacts current before implementation or PR handoff.",
			"- If `namba regen` or `namba sync` changes generated instruction surfaces, start a fresh Codex session so the updated guidance is loaded before continuing a long repair loop.",
			"- Missing review passes stay advisory by default: `namba run`, `namba sync`, and `namba pr` surface the current readiness summary without silently hard-blocking delivery.",
			"",
			"## Key generated assets",
			"",
			"- `.namba/`: config, SPEC packages, project docs, logs",
			"- `.namba/specs/<SPEC>/reviews/`: advisory product, engineering, design, and readiness artifacts for each SPEC",
			"- `.agents/skills/`: repo-local skills used directly by Codex",
			"- `.codex/config.toml`: repo-local Codex defaults plus any configured Namba-managed MCP presets",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"- `.namba/project/*`: change summary, release notes, checklist, codemap",
			"",
			"## Collaboration defaults",
			"",
			"- Work happens on dedicated branches.",
			"- `namba pr` targets `main` and keeps the configured PR language plus review marker aligned.",
			"- `namba land` merges only clean PRs and updates local `main` without clobbering unrelated work.",
			"- GitHub review requests use `@codex review`.",
			"",
			"## Release flow",
			"",
			"- `namba release` requires a clean working tree on `main`.",
			"- `--push` pushes both the new tag and `main`, then triggers the GitHub Release workflow.",
			"",
		}, "\n")
	}
}

func renderManagedProjectGettingStarted(lang string, projectCfg projectConfig) string {
	projectName := projectCfg.Name
	if projectName == "" {
		projectName = "this repository"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 저장소 열기",
			"",
			fmt.Sprintf("- `%s` 루트에서 Codex를 시작하세요.", projectName),
			"- 빠른 준비 상태 점검이 필요하면 `namba doctor`를 실행하세요.",
			"",
			"## 2. 현재 컨텍스트 갱신",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 작업 패키지 만들기",
			"",
			"- 기능 요청: `namba plan \"description\"`",
			"- 버그 수정 SPEC 계획: `namba fix --command plan \"issue description\"`",
			"- 현재 workspace에서 직접 버그 수정: `namba fix \"issue description\"` 또는 `namba fix --command run \"issue description\"`",
			"",
			"## 4. 계획 준비도 검토",
			"",
			"- 코딩 전에 product, engineering, design 관점 검토가 필요하면 `$namba-plan-pm-review`, `$namba-plan-eng-review`, `$namba-plan-design-review`를 사용하세요.",
			"- `namba run`과 `namba pr` 전에 `.namba/specs/<SPEC>/reviews/readiness.md`를 최신 상태로 유지하세요.",
			"",
			"## 5. 구현 및 sync",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 6. 인계 및 머지",
			"",
			"```text",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. リポジトリを開く",
			"",
			fmt.Sprintf("- `%s` のルートから Codex を開始してください。", projectName),
			"- すばやい準備状態チェックが必要なら `namba doctor` を実行してください。",
			"",
			"## 2. 現在のコンテキストを更新",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 作業パッケージを作る",
			"",
			"- 機能要求: `namba plan \"description\"`",
			"- バグ修正 SPEC の計画: `namba fix --command plan \"issue description\"`",
			"- 現在の workspace で直接バグ修正: `namba fix \"issue description\"` または `namba fix --command run \"issue description\"`",
			"",
			"## 4. 計画の準備度を確認",
			"",
			"- 実装前に product / engineering / design の観点レビューが必要なら `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` を使ってください。",
			"- `namba run` と `namba pr` の前に `.namba/specs/<SPEC>/reviews/readiness.md` を最新に保ってください。",
			"",
			"## 5. 実装と sync",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 6. 引き渡しとマージ",
			"",
			"```text",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. 打开仓库",
			"",
			fmt.Sprintf("- 从 `%s` 根目录启动 Codex。", projectName),
			"- 如果需要快速检查准备状态，可以运行 `namba doctor`。",
			"",
			"## 2. 刷新当前上下文",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. 创建工作包",
			"",
			"- 功能请求: `namba plan \"description\"`",
			"- 规划缺陷修复 SPEC: `namba fix --command plan \"issue description\"`",
			"- 在当前 workspace 直接修复缺陷: `namba fix \"issue description\"` 或 `namba fix --command run \"issue description\"`",
			"",
			"## 4. 检查计划准备度",
			"",
			"- 如果在编码前需要 product / engineering / design 视角的评审，请使用 `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review`。",
			"- 在 `namba run` 和 `namba pr` 之前，请保持 `.namba/specs/<SPEC>/reviews/readiness.md` 为最新状态。",
			"",
			"## 5. 实现并 sync",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 6. 交接与合并",
			"",
			"```text",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "getting-started")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			"## 1. Open the repository",
			"",
			fmt.Sprintf("- Start Codex from the root of `%s`.", projectName),
			"- On Windows, prefer a WSL workspace when you want the best Codex CLI behavior inside the repository.",
			"- Run `namba doctor` if you want a quick readiness check.",
			"",
			"## 2. Refresh current context",
			"",
			"```text",
			"namba project",
			"```",
			"",
			"## 3. Create a work package",
			"",
			"- Feature request: `namba plan \"description\"`",
			"- Bugfix SPEC planning: `namba fix --command plan \"issue description\"`",
			"- Direct repair in the current workspace: `namba fix \"issue description\"` or `namba fix --command run \"issue description\"`",
			"",
			"## 4. Review plan readiness",
			"",
			"- Use `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` when a SPEC needs product, engineering, or design critique before coding starts.",
			"- Keep `.namba/specs/<SPEC>/reviews/readiness.md` current so review depth stays visible before `namba run` and `namba pr`.",
			"",
			"## 5. Implement and sync",
			"",
			"```text",
			"namba run SPEC-001",
			"namba sync",
			"```",
			"",
			"## 6. Hand off and merge",
			"",
			"```text",
			"namba pr \"work description\"",
			"namba land",
			"```",
			"",
		}, "\n")
	}
}

func renderManagedProjectWorkflowGuide(lang string, projectCfg projectConfig, profile initProfile) string {
	projectName := projectCfg.Name
	if projectName == "" {
		projectName = "this repository"
	}
	switch normalizeReadmeLanguage(lang) {
	case "ko":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s`는 NambaAI 규칙으로 관리됩니다.", projectName),
			"",
			"## 핵심 위치",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.namba/specs/<SPEC>/reviews/`: 현재 SPEC의 advisory product, engineering, design, readiness artifact",
			"- `.agents/skills/`: Codex가 직접 쓰는 skills",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## 작업 순서",
			"",
			"1. `namba project`",
			"2. `namba plan` 또는 `namba fix --command plan`",
			"3. 필요하면 관련 plan-review skill을 실행하고 `.namba/specs/<SPEC>/reviews/readiness.md`를 갱신",
			"4. `namba run SPEC-XXX`",
			"5. `namba sync`",
			"6. `namba pr \"review title\"`",
			"7. `namba land`",
			"",
			"## `namba plan`과 `namba fix`",
			"",
			"- `namba plan \"description\"`: 다음 기능 SPEC 패키지와 review artifact를 만듭니다.",
			"- `namba fix --command plan \"issue description\"`: 버그 수정 SPEC 패키지와 review artifact를 만듭니다.",
			"- `namba fix \"issue description\"`: 현재 workspace에서 direct repair를 시작합니다.",
			"- `namba fix --command run \"issue description\"`: 같은 direct-repair 경로를 명시적으로 선택합니다.",
			"- `namba plan --help`와 `namba fix --help`: read-only help/option probing 경로이며 SPEC를 만들지 않습니다.",
			"",
			"## Run 모드",
			"",
			"- `namba run SPEC-XXX`: 하나의 workspace에서 실행하는 표준 standalone Codex 흐름입니다.",
			"- `namba run SPEC-XXX --solo`: 하나의 workspace에서 단일 runner를 사용합니다.",
			"- `namba run SPEC-XXX --team`: 같은 workspace의 멀티에이전트 실행입니다.",
			"- `namba run SPEC-XXX --parallel`: Codex subagent orchestration이 아니라 Namba-managed git worktree fan-out/fan-in 입니다.",
			"",
			"## 역할 라우팅",
			"",
			"- 기본 `namba run`은 specialist 신호가 강하지 않으면 standalone runner에 남습니다.",
			"- `--solo`는 한 명의 specialist로 위험을 줄일 수 있을 때만 분기하고, `--team`은 여러 specialist와 마지막 reviewer를 같은 workspace 안에서 조율합니다.",
			"- UI / responsive / mobile / design은 `namba-frontend-implementer`, `namba-mobile-engineer`, `namba-designer`로, API / schema / pipeline은 `namba-backend-implementer`, `namba-data-engineer`로, auth / secrets / compliance는 `namba-security-engineer`로, deployment / runtime은 `namba-devops-engineer`로 보냅니다.",
			"- standalone runner는 integrator와 validation owner를 맡고, final acceptance는 `namba-reviewer`가 담당합니다.",
			"",
			"## 리뷰 준비도",
			"",
			"- `namba plan`과 `namba fix --command plan`은 `.namba/specs/<SPEC>/reviews/product.md`, `engineering.md`, `design.md`, `readiness.md`를 seed 합니다.",
			"- 구현이나 GitHub handoff 전에 `$namba-plan-pm-review`, `$namba-plan-eng-review`, `$namba-plan-design-review`로 review 산출물을 최신 상태로 유지하세요.",
			"- `namba regen` 또는 `namba sync`가 생성된 instruction surface를 바꾸면, 긴 repair loop 전에 fresh Codex session을 시작해 갱신된 지침을 다시 읽어오세요.",
			"- 리뷰 통과가 빠져 있어도 advisory 상태를 유지합니다. `namba run`, `namba sync`, `namba pr`는 readiness 요약을 노출하지만 hard gate로 삼지는 않습니다.",
			"",
			"## 협업 규칙",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"- `namba sync`는 로컬 산출물 갱신에 머물고, `namba pr`와 `namba land`가 GitHub handoff와 merge를 담당합니다.",
			"",
		}, "\n")
	case "ja":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` は NambaAI の規約で管理されています。", projectName),
			"",
			"## 主要な場所",
			"",
			"- `.namba/`: config、specs、project docs",
			"- `.namba/specs/<SPEC>/reviews/`: 現在の SPEC に対する advisory product / engineering / design / readiness artifact",
			"- `.agents/skills/`: Codex が直接使う skills",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## 作業順序",
			"",
			"1. `namba project`",
			"2. `namba plan` または `namba fix --command plan`",
			"3. 必要なら関連する plan-review skill を実行し、`.namba/specs/<SPEC>/reviews/readiness.md` を更新",
			"4. `namba run SPEC-XXX`",
			"5. `namba sync`",
			"6. `namba pr \"review title\"`",
			"7. `namba land`",
			"",
			"## `namba plan` と `namba fix`",
			"",
			"- `namba plan \"description\"`: 次の機能 SPEC パッケージと review artifact を作成します。",
			"- `namba fix --command plan \"issue description\"`: バグ修正 SPEC パッケージと review artifact を作成します。",
			"- `namba fix \"issue description\"`: 現在の workspace で direct repair を始めます。",
			"- `namba fix --command run \"issue description\"`: 同じ direct-repair path を明示的に選びます。",
			"- `namba plan --help` と `namba fix --help`: read-only の help / option probing であり、SPEC を作成しません。",
			"",
			"## Run モード",
			"",
			"- `namba run SPEC-XXX`: 1 つの workspace で動く標準 standalone Codex flow です。",
			"- `namba run SPEC-XXX --solo`: 1 つの workspace で単一 runner を使います。",
			"- `namba run SPEC-XXX --team`: 同じ workspace の multi-agent execution です。",
			"- `namba run SPEC-XXX --parallel`: Codex subagent orchestration ではなく、Namba-managed git worktree fan-out/fan-in です。",
			"",
			"## ロールルーティング",
			"",
			"- 既定の `namba run` は、specialist signal が強くない限り standalone runner に留まります。",
			"- `--solo` は 1 人の specialist でリスクを下げられる場合だけ分岐し、`--team` は複数 specialist と最終 reviewer を同じ workspace 内で調整します。",
			"- UI / responsive / mobile / design は `namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer` に、API / schema / pipeline は `namba-backend-implementer`、`namba-data-engineer` に、auth / secrets / compliance は `namba-security-engineer` に、deployment / runtime は `namba-devops-engineer` に割り当てます。",
			"- standalone runner は integrator と validation owner を担い、final acceptance は `namba-reviewer` が担当します。",
			"",
			"## レビュー準備度",
			"",
			"- `namba plan` と `namba fix --command plan` は `.namba/specs/<SPEC>/reviews/product.md`、`engineering.md`、`design.md`、`readiness.md` を seed します。",
			"- 実装または GitHub handoff の前に `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` で review artifact を最新に保ってください。",
			"- `namba regen` または `namba sync` が生成された instruction surface を変えた場合は、長い repair loop の前に fresh Codex session を開始して更新済み guidance を読み直してください。",
			"- review pass が欠けていても advisory のままです。`namba run`、`namba sync`、`namba pr` は readiness summary を表示しますが hard gate にはしません。",
			"",
			"## 協業ルール",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"- `namba sync` はローカル成果物の更新にとどまり、`namba pr` と `namba land` が GitHub handoff と merge を担当します。",
			"",
		}, "\n")
	case "zh":
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` 由 NambaAI 约定管理。", projectName),
			"",
			"## 关键位置",
			"",
			"- `.namba/`: config、specs、project docs",
			"- `.namba/specs/<SPEC>/reviews/`: 当前 SPEC 的 advisory product / engineering / design / readiness artifact",
			"- `.agents/skills/`: Codex 直接使用的 skills",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## 工作顺序",
			"",
			"1. `namba project`",
			"2. `namba plan` 或 `namba fix --command plan`",
			"3. 必要时执行相关 plan-review skill，并更新 `.namba/specs/<SPEC>/reviews/readiness.md`",
			"4. `namba run SPEC-XXX`",
			"5. `namba sync`",
			"6. `namba pr \"review title\"`",
			"7. `namba land`",
			"",
			"## `namba plan` 和 `namba fix`",
			"",
			"- `namba plan \"description\"`: 创建下一个功能 SPEC 包和 review artifact。",
			"- `namba fix --command plan \"issue description\"`: 创建缺陷修复 SPEC 包和 review artifact。",
			"- `namba fix \"issue description\"`: 在当前 workspace 启动 direct repair。",
			"- `namba fix --command run \"issue description\"`: 显式选择同一个 direct-repair 路径。",
			"- `namba plan --help` 和 `namba fix --help`: 属于 read-only 的 help / option probing，不会创建 SPEC。",
			"",
			"## Run 模式",
			"",
			"- `namba run SPEC-XXX`: 在单一 workspace 中运行的标准 standalone Codex flow。",
			"- `namba run SPEC-XXX --solo`: 在单一 workspace 中使用单 runner。",
			"- `namba run SPEC-XXX --team`: 同一 workspace 内的 multi-agent execution。",
			"- `namba run SPEC-XXX --parallel`: 这不是 Codex subagent orchestration，而是 Namba-managed git worktree fan-out/fan-in。",
			"",
			"## 角色路由",
			"",
			"- 默认 `namba run` 会停留在 standalone runner，除非 specialist signal 足够强。",
			"- `--solo` 只在一个 specialist 能明显降低风险时才分流，`--team` 会在同一 workspace 内协调多个 specialist 和最终 reviewer。",
			"- UI / responsive / mobile / design 交给 `namba-frontend-implementer`、`namba-mobile-engineer`、`namba-designer`；API / schema / pipeline 交给 `namba-backend-implementer`、`namba-data-engineer`；auth / secrets / compliance 交给 `namba-security-engineer`；deployment / runtime 交给 `namba-devops-engineer`。",
			"- standalone runner 继续担任 integrator 和 validation owner，final acceptance 由 `namba-reviewer` 负责。",
			"",
			"## 评审准备度",
			"",
			"- `namba plan` 和 `namba fix --command plan` 会 seed `.namba/specs/<SPEC>/reviews/product.md`、`engineering.md`、`design.md`、`readiness.md`。",
			"- 在实现或 GitHub handoff 之前，使用 `$namba-plan-pm-review`、`$namba-plan-eng-review`、`$namba-plan-design-review` 保持 review artifact 最新。",
			"- 如果 `namba regen` 或 `namba sync` 改变了生成的 instruction surface，请在长 repair loop 之前启动 fresh Codex session，重新加载更新后的 guidance。",
			"- 即使 review pass 缺失，默认也保持 advisory。`namba run`、`namba sync`、`namba pr` 会展示 readiness summary，但不会变成 hard gate。",
			"",
			"## 协作规则",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"- `namba sync` 只负责刷新本地产物，`namba pr` 和 `namba land` 负责 GitHub handoff 和 merge。",
			"",
		}, "\n")
	default:
		return strings.Join([]string{
			renderGeneratedDocHeader(),
			fmt.Sprintf("# %s", localizeGuideLabel(lang, "workflow-guide")),
			"",
			renderLanguageLinks("../"),
			"",
			renderDocLinkBar(lang),
			"",
			fmt.Sprintf("`%s` is managed with NambaAI conventions.", projectName),
			"",
			"## Key locations",
			"",
			"- `.namba/`: config, specs, project docs",
			"- `.namba/specs/<SPEC>/reviews/`: advisory product, engineering, design, and readiness artifacts for the current SPEC",
			"- `.agents/skills/`: skills used directly by Codex",
			"- `.codex/agents/*.toml`: project-scoped custom agents",
			"",
			"## Work order",
			"",
			"1. `namba project`",
			"2. `namba plan` or `namba fix --command plan`",
			"3. Run the relevant plan-review skills and refresh `.namba/specs/<SPEC>/reviews/readiness.md` when the SPEC needs product, engineering, or design critique",
			"4. `namba run SPEC-XXX`",
			"5. `namba sync`",
			"6. `namba pr \"review title\"`",
			"7. `namba land`",
			"",
			"## `namba plan` and `namba fix`",
			"",
			"- `namba plan \"description\"`: create the next feature SPEC package and review artifacts.",
			"- `namba fix --command plan \"issue description\"`: create a bugfix SPEC package plus review artifacts.",
			"- `namba fix \"issue description\"`: direct repair in the current workspace.",
			"- `namba fix --command run \"issue description\"`: explicit form of the same direct-repair path.",
			"- `namba plan --help` and `namba fix --help`: read-only help and option discovery; they must not create a SPEC package.",
			"",
			"## Run modes",
			"",
			"- `namba run SPEC-XXX`: standard standalone Codex flow in one workspace.",
			"- `namba run SPEC-XXX --solo`: a single runner in one workspace.",
			"- `namba run SPEC-XXX --team`: same-workspace multi-agent execution.",
			"- `namba run SPEC-XXX --parallel`: Namba-managed git worktree fan-out/fan-in, not Codex subagent orchestration.",
			"",
			"## Role routing",
			"",
			"- Default `namba run` stays inside the standalone runner unless specialist signals are strong enough to justify delegation.",
			"- `--solo` keeps the run inside one runner unless a single specialist would materially reduce risk.",
			"- `--team` keeps the work in one workspace while coordinating multiple specialists plus a final reviewer when acceptance spans multiple domains.",
			"- Route UI, responsive, mobile, and design work to `namba-frontend-implementer`, `namba-mobile-engineer`, or `namba-designer`; API, schema, and pipeline work to `namba-backend-implementer` or `namba-data-engineer`; auth, secrets, and compliance work to `namba-security-engineer`; deployment and runtime work to `namba-devops-engineer`.",
			"- Keep the standalone runner as integrator and validation owner, and use `namba-reviewer` last when multiple specialists contribute.",
			"",
			"## Review readiness",
			"",
			"- `namba plan` and `namba fix --command plan` seed `.namba/specs/<SPEC>/reviews/product.md`, `engineering.md`, `design.md`, and `readiness.md`.",
			"- `$namba-plan-pm-review`, `$namba-plan-eng-review`, and `$namba-plan-design-review` keep those artifacts current before execution or GitHub handoff.",
			"- If `namba regen` or `namba sync` changes generated instruction surfaces, start a fresh Codex session so the updated guidance is loaded before continuing a long repair loop.",
			"- Review readiness is advisory by default: missing review passes are surfaced clearly by `namba run`, `namba sync`, and `namba pr`, but they do not silently become a hard gate.",
			"",
			"## Collaboration rules",
			"",
			fmt.Sprintf("- base branch: `%s`", branchBase(profile)),
			fmt.Sprintf("- PR base: `%s`", prBaseBranch(profile)),
			fmt.Sprintf("- PR language: %s", humanLanguageName(profile.PRLanguage)),
			fmt.Sprintf("- review request: `%s`", codexReviewComment(profile)),
			"- `namba sync` stays local; `namba pr` and `namba land` handle GitHub handoff plus merge.",
			"",
		}, "\n")
	}
}
